### ISSUE TITLE
Plugin List Breaks On Activation

### ISSUE THREAD

**Issue by mattsaler** [TobiasBg/TablePress#10]
I installed this plugin on one of our client sites running WP3.8 and found that the Plugins list in WP was broken when TablePress was activated: only Akismet would display in the All list, though the other plugins were available via search. The error logs file gave this error: 

[timestamp] [error] [client IP] PHP Catchable fatal error:  Argument 1 passed to TablePress_Admin_Controller::add_plugin_row_meta() must be an array, null given in /path/to/site/wp-content/plugins/tablepress/controllers/controller-admin.php on line 288, referer: http://client.company.com/wp-admin/plugins.php?plugin_status=active

Our developer took a look and made a fix. His notes below: 

"The 'array $links, $file' parameters had no values when the function was called. The $links array is actually populated in the function itself, so there would be no values to pass as a function parameter. I don't know what the purpose behind the if ( TABLEPRESS_BASENAME == $file ) { } conditional was, but apparently there was no value assigned to the $file parameter either because with that conditional in there the Plugin Meta Data links weren't being shown on the Plugins page, which says the TABLEPRESS_BASENAME did NOT equal $file, which would be NULL."

He removed the parameters in the function and removed the conditional statement—but maybe that's not a long-term fix.

**Comment by sunyleone** [comment]
very most thanks mr tobias .can u do 1 thing  ?
add compare parameter to search
example -
1 field --         NAME
2 FIELD --      NUMERICAL VALUE (123)
3.   SEARCH

**Comment by TobiasBg** [comment]
Hi,

I'm really sorry, but something like that is not really possible :-( I hope that TablePress is still useful to you!

Best wishes,
Tobias
