### ISSUE TITLE
Import of csv containing <a href> in an cell fails

### ISSUE THREAD

**Issue by OliEderGP** [TobiasBg/TablePress#101]
I have a table with cells containing URLs to specific sites. The URLs are to long to just use the autolink extension so I changed the content of the cells to <a href="URL">link</a>.
If I try to import this csv the import doesn't start, instead a download of the admin_post.php is triggered.
If zip the csv the table gets imported, but alle options are ignored and a new table is being created even if I checkt "overwrite" or "add to table".

I just looked into the admin-post.php and it is an 503 message.

**Comment by OliEderGP** [comment]
It was a problem with the structure of the csv itself. Quoting all Table-Cells und and changing the Field Seperator to comma instead of semicolon fixed the issue for me. So feel free to close the issue.

**Comment by TobiasBg** [comment]
Hi @OliEderGP,

good to hear that it's working now! Note that the problem with the offered download of the admin-post.php file is most likely caused by the server configuration, not by TablePress.

Best wishes,
Tobias

**Comment by OliEderGP** [comment]
Okay, I just retried it with an other table and now the problem is back up. But good to know that I should look into the server config. ;)

**Comment by TobiasBg** [comment]
Hi,

you should check the error log file here. Most likely it's a server security software that doesn't like the request (maybe because of the size or the content of the request). It then blocks the request, which could lead to this issue.

Regards,
Tobias
