### ISSUE TITLE
PHP 7 compatibility issues (pending fix)

### ISSUE THREAD

**Issue by UXUIStack** [TobiasBg/TablePress#102]
FILE: /wp-content/plugins/tablepress/libraries/excel-reader.class.php

FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES

 222 | WARNING | Method name "OLERead::__readData" is discouraged; PHP has reserved all method names with a double underscore prefix for future use.
 240 | WARNING | Method name "OLERead::__readPropertySets" is discouraged; PHP has reserved all method names with a double underscore prefix for future use.

FILE: /wp-content/plugins/tablepress/views/view-about.php

FOUND 2 ERRORS AFFECTING 2 LINES

 186 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 187 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead

**Comment by TobiasBg** [comment]
Hi @UXUIStack,

thanks for your report! There's nothing to worry about here though :-) TablePress is compatible and takes necessary precautions. Please see https://wordpress.org/support/topic/is-tablepress-compatible-with-php-7-and-php-7-1/ for more details.

Best wishes,
Tobias
