### ISSUE TITLE
Hey Tobias,

### ISSUE THREAD

**Issue by shariq02ca** [TobiasBg/TablePress#105]
I am also trying to figure this one out. 

An example would be. 
https://10beasts.com/best-wireless-earbuds/

In the aforementioned website, on a mobile you can see the column 2 and 3 are collapsed whereas we can see column 0, 1, and 4.

I tried following your examples but since I am not a coder really struggling with it.

Any help would be well appreciated.

Best Regards,
Shaq

_Originally posted by @shariq02ca in https://github.com/TobiasBg/TablePress/issue_comments#issuecomment-443565345_

**Comment by TobiasBg** [comment]
Hi @shariq02ca,

did this help?

Regards,
Tobias
