### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by elzarifb** [TobiasBg/TablePress#107]
Hello Tobias, 

I'm trying to add a JSON feed to one of my tables, but it keeps losing the header and displays all of the variables coded into that stream. 

1 - Is there a way to fix the losing header? 
2 - Is there a way to select which variables we want to show from the feed ?

Thanks!

**Comment by TobiasBg** [comment]
Hi @elzarifb,

just to be sure that I understand: You are talking about importing a TablePress table from a file here?

Note that the JSON format will then have to be in a specific format that TablePress understands. For that, I recommend to create a small example table in TablePress and export it to a JSON file, and then inspect the syntax.

Regards,
Tobias

**Comment by elzarifb** [comment]
@TobiasBg 

Yes I am hoping to insert a JSON feed into a table made with Tablepress. So, I will try your suggestion and hopefully get to a solution. 

Thanks!

**Comment by TobiasBg** [comment]
Hi @elzarifb,

no problem! I hope you can make it work!

Best wishes,
Tobias
