### ISSUE TITLE
problem with hiding empty rows

### ISSUE THREAD

**Issue by torpheh** [TobiasBg/TablePress#108]
I am filling a tablepress table using shortcods and this piece of code :
    
    add_shortcode('custom_acf',custom_acf_callback);
    function custom_acf_callback ($atts = '')
      {
      $value = shortcode_atts( array(
        'my_field' => '',
       ), $atts );
     //the main part starts from here:
       if ($custom_acf_value){
    
            return $custom_acf_value;
        }
        else {
    //and the problem is here:
            return '';
        }

and I am hiding the empty table cells using this tricky css code:</br>
    
    td:empty {
    display: none;
    }
The **Problem** is that the empty cells will not be hidden.H have created a table and added myshortcode that is [custom_acf] in every table rows.
if I don't put my shortcode in table rows, the CSS code works great and hides the empty cells.
I have also tried these ideas to return empty for novalue cells but no success:
- return NULL;
- return;
- echo "";
- not using else and just if
- return an empty array

**Comment by TobiasBg** [comment]
Hi @torpheh,

this is not really a TablePress issue, but more of a CSS issue. For example, make sure that there are no other characters (like spaces or line breaks before or after the Shortcode).
Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by torpheh** [comment]
thank you man you are always helpful. 
actually suddenly I saw there is an unwanted **`<br>`** in empty cells and I don't know why.<br>
after that I have tested this code to prevent **`<br>`** in table cells, the code now is somthing like this but not exactly and works good:</br>
    
    $my_empty = "";
    $my_nobr = strip_tags($my_empty, '<p><a>');
    return $my_nobr;
I guess the reason is in **WordPress**  functions but I did not go deeper and there was no need, this code solved my problem.

**Comment by TobiasBg** [comment]
Hi @torpheh,

great! That's good to hear!

Best wishes,
Tobias
