### ISSUE TITLE
Dataset Not Refreshing

### ISSUE THREAD

**Issue by Surfing-Chef** [TobiasBg/TablePress#109]
I currently use ACF to create a summary box in my sidebar. I use then use the Tablepress plugin to build a table that displays the dataset built on the post page. Everything works great when using a laptop or a desktop browser but when I browse using an iphone (both chrome and safari), the datasets do not reflect the current post.

Specifically:

When I look between this page: https://www.surfing-chef.com/alsace-grapes-soil/
and this one: https://www.surfing-chef.com/champagne/

The summary section from the sidebar does not change when veiwed on my iphone.

Any thoughts?

**Comment by TobiasBg** [comment]
Hi @Surfing-Chef,

thanks for your post, and sorry for the trouble.

Is the data in the table loaded via an ACF Shortcode? If so, you are probably running into caching issues here. Please try using this modified Shortcode in the sidebar:
`[table id=12 cache_table_output=false /]
`
Regards,
Tobias
