### ISSUE TITLE
[Security] Vulnerability Report

### ISSUE THREAD

**Issue by xpirt** [TobiasBg/TablePress#112]
Hello Tobias,

I've found that Persistent Cross-Site Scripting (Stored XSS) is possible in the latest version of TablePress, do you have any contact to send you technical details about it?

Andrei

**Comment by TobiasBg** [comment]
Hi @xpirt,

thanks for your post! Yes, please send me an email, the address is in the main file "tablepress.php". Thanks!

Regards,
Tobias

**Comment by xpirt** [comment]
Just sent an email. Closing this.

Andrei

**Comment by TobiasBg** [comment]
Hi,

just for everybody maybe seeing this issue: After investigating this some more, we found that everything is as expected here. This is the same behavior as https://make.wordpress.org/core/handbook/testing/reporting-security-vulnerabilities/#why-are-some-users-allowed-to-post-unfiltered-html

Best wishes,
Tobias
