### ISSUE TITLE
Is the Editor included?

### ISSUE THREAD

**Issue by samjco** [TobiasBg/TablePress#113]
Is the editor ext included to edit rows?
If not, how can the Editor be added?
https://editor.datatables.net/examples/advanced/REST.html

**Comment by TobiasBg** [comment]
Hi @samjco,

no, the DataTables Editor add-on is not integrated in TablePress, simply because it is not a free tool.
Unfortunately, I have never really looked at it, so that I don't know if or how it could be integrated, sorry.

Regards,
Tobias

**Comment by samjco** [comment]
It would be nice to add support for this.
https://editor.datatables.net/manual/multi-row#Developers

**Comment by TobiasBg** [comment]
Hi,

unfortunately, that won't really be possible, simply due to the Editor add-on not being fully open source as it would be necessary for distribution with a GPL plugin. I'm really sorry.

Best wishes,
Tobias
