### ISSUE TITLE
Adding dynamic JSON url

### ISSUE THREAD

**Issue by samjco** [TobiasBg/TablePress#114]
So I know that in the plugin we can add in the URL to the JSON file...
Will this work with dynamic URL such as WP REST API URL?

**Comment by TobiasBg** [comment]
Hi @samjco,

this depends: If the URL to the JSON file returns the proper format for a TablePress table (a two-dimensional array), this will work. However, regular responses from APIs often don't follow that, so that you'd need some extra code in between.

Regards,
Tobias

**Comment by samjco** [comment]
Yes I did notice that!

But the rest routes plugin seems to work fine with other tables. As it statically converts from serialized form. So I'm thinking that that plugin will work for yours

**Comment by samjco** [comment]
https://wordpress.org/plugins/rest-routes/

**Comment by TobiasBg** [comment]
Hi,

I'm not sure that I understand. Do you want to offer the table data (as JSON) via the REST API? Or do you want to import tables from JSON URLs? Unfortunately, the Rest Routes plugin alone will not be sufficient for the first scenario and it is unrelated to the import functions of TablePress.

Regards,
Tobias

**Comment by samjco** [comment]
Well, using WP REST API doesn't work yet because of the 2-dimensional array issue. 
However, the REST ROUTES plugin does work because it divys up the data in a 2-dimensional array to be imported easily into Datatables

**Comment by TobiasBg** [comment]
Hi,

this seems to be a rather specific use case, and I don't think that it will be helpful to the big majority of users, as you'd still need some custom coding and integration. I'm not sure that I'll find the time to implement something like this, sorry.

Regards,
Tobias

**Comment by samjco** [comment]
So I just attempt to use the Rest-route url to import data into Tablepress and it worked!!!
Question is. Is this table dynamically built? Meaning if I change a column in Rest-Routes it will change in Tablepress datatable?

**Comment by TobiasBg** [comment]
Hi,

awesome! Great to hear that it worked! :-)

And no, the table data will not update automatically, this was a one-time import. For periodic updates, you could try https://tablepress.org/extensions/table-auto-import/

Best wishes,
Tobias
