### ISSUE TITLE
User query-based results

### ISSUE THREAD

**Issue by jebthomas** [TobiasBg/TablePress#115]
How do I enable query-based results for this plugin? I have a large database of products and want visitors to only see what they search in the query field.

Awesome plugin by the way, if I can get it to work I'll definitely donate to the cause.

**Comment by TobiasBg** [comment]
hi @jebthomas,

besides the integrated JavaScript-based filtering, your best chance for this might be to use the TablePress Extension from https://tablepress.org/extensions/row-filter/, together with the TablePress Extension from https://tablepress.org/extensions/shortcode-filter-get-parameter/ and a custom form.

Please see https://wordpress.org/support/topic/search-from-another-page/ for some details on this.

Regards,
Tobias
