### ISSUE TITLE
loading and pagination

### ISSUE THREAD

**Issue by ssjogus** [TobiasBg/TablePress#117]
hi, 

thanks for this wonderful plugin.. is there any way to show a loading icon before table gets displayed, because n case of large tables it becomes a problem.

secondly, is there any way to show the pagination buttons?

otherwise the plugin works just great..

thanks in advance..

**Comment by TobiasBg** [comment]
Hi @ssjogus,

no, sorry, I'm not aware of a way to show a loading animation :-(

And can you clarify what you mean with "secondly, is there any way to show the pagination buttons?"
If pagination is enabled, you should have the corresponding control links below the table.

Regards,
Tobias

**Comment by ssjogus** [comment]
hi,

thanks for the  reply..

by navigation button , i mean the page numbers 1,2,3,..... Currently only prev and next buttons are coming. in case of huge tables with many records, the navigation page numbers will be helpful.

regards,

ssjogus

**Comment by TobiasBg** [comment]
Hi @ssjogus,

thanks for the explanation! This can be achieved by adding a "Custom Command" on the table's "Edit" screen, like
`"pagingType": "full_numbers"`
For all possible options, please see https://datatables.net/reference/option/pagingType

Regards,
Tobias
