### ISSUE TITLE
Attendance list 

### ISSUE THREAD

**Issue by mybestrong** [TobiasBg/TablePress#119]
I use my members list from Wordpress as an attendance sheet for my meetings.

This means exporting them to excel and printing a weekly list that I take to the meetings and write a tick against their name.

Could table press list my members on a page and I could apply a tick that gets recorded somewhere?

**Comment by TobiasBg** [comment]
Hi @mybestrong,

thanks for your question! Unfortunately, it's not directly possible to use such an interface on the website. The only way to edit the tables would be on the "Edit" screen in the admin area.

Regards,
Tobias
