### ISSUE TITLE
Gutenberg support

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#121]
It would be nice if TablePress tables can be inserted (and even edited/updated inline) as Gutenberg blocks into Gutenberg editor.

**Comment by TobiasBg** [comment]
Hi @strarsis,

support for a Gutenberg block is indeed already on my list of ideas for a future release. I'm currently doing research on how to develop this. Due to time constraints, it will however still take time until something is available.

Best wishes,
Tobias

**Comment by shaunroselt** [comment]
Any feedback on this?

I hate the way you have to edit TablePress tables. Would much rather prefer a Gutenberg block.

**Comment by UnicornXP** [comment]
I would also like support for Gutenburg blocks.

**Comment by TobiasBg** [comment]
Hi @shaunroselt and @UnicornXP,

thanks for your interest here! The soon-to-be-released TablePress 2.0 will indeed come with a Gutenberg block! For starters, it will however only be a replacement for the Shortcode, and will not yet allow direct editing from within the Block Editor. However, the "Edit" screen will also get a major overhaul in TablePress 2.0, which will make editing tables much easier and faster!
I don't yet have a definite date for the release of TablePress 2.0, but I'm aiming for the late second quarter at the moment. I hope to be able to share an introduction and announcement on tablepress.org soon!

Best wishes,
Tobias

**Comment by shaunroselt** [comment]
Thanks. That's fantastic. My biggest issue with TablePress is the creation and editing of tables. It's so much faster to make a Gutenberg table compared to TablePress table, but then obviously you miss out on the TablePress functionality.
