### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by chrislow** [TobiasBg/TablePress#122]
We need to update the plugin, because it is using the deprecated `strpos()` function.
Right now the following error-message is thrown, when the plugin is installed on the newest wordpress version with PHP 7.3.10.

> Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. 
> Use an explicit chr() call to preserve the current behavior in 
> wp-content/plugins/tablepress-datatables-fixedcolumns/libraries/plugin-update-checker.php on line 851

https://www.php.net/manual/en/function.strpos.php

I can open a pull request if you want.

**Comment by TobiasBg** [comment]
Hi @chrislow,

thanks for your report! From what I can see, not the `strpos()` function is the problem, but that the parameter `$needle` is passed in the wrong way (not as a string). Thus, we should find out why that parameter is not a string... Do you have any idea on that?

Regards,
Tobias

**Comment by chrislow** [comment]
Hi @TobiasBg ,

i just saw, that the error occurred in on of the extensions of TablePress. Is there a separate repository for the extension or which file do we talk about in this repo?

`tablepress-datatables-fixedcolumns/libraries/plugin-update-checker.php `
Thats the file the stack-trace showed to me.

**Comment by TobiasBg** [comment]
Hi,

yes, this is from a TablePress Extension. These are not in a public git repository at this time though.

The line with the error seems to using the result of the constant `WPMU_PLUGIN_DIR`. My guess right now is that this not defined in your (and probably most) WordPress installation.
However, as the method that is using this is not really needed from what I can see, I'll probably just remove that.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

I have fixed this in the Extension's code. The next release will contain a fix for this notice.

Thanks again for the report!
Best wishes,
Tobias
