### ISSUE TITLE
Fatal Error when checking for updates when Cron jobs are running

### ISSUE THREAD

**Issue by madjon** [TobiasBg/TablePress#123]
https://github.com/TobiasBg/TablePress/blob/790c7736511de2761efbdcee44c28e2c6cde744b/classes/class-controller.php#L89

![image](https://user-images.githubusercontent.com/31717797/71063754-23b5ba00-21b9-11ea-9efa-d16b3f7af4b2.png)

I am spawning cron jobs to process some data in the database. These cron jobs fall over when the above update check runs.

**Comment by TobiasBg** [comment]
Hi @madjon,

thanks for the report! From what I can see in the screenshot, the plugin "AJAX Search Pro" seems to play a role here, as it's the one that is calling and loading TablePress.
My guess here is that it's loading TablePress incompletely, namely without initialising the options.
In particular, it's most likely missing the lines
```PHP
TablePress::$model_options = TablePress::load_model( 'options' );
TablePress::$model_table = TablePress::load_model( 'table' );
```
and only has something like
```PHP
TablePress::$controller = TablePress::load_controller( 'frontend' );
```
Can you maybe check that in that plugin.

Regards,
Tobias

**Comment by madjon** [comment]
Hi @TobiasBg 

Thanks for getting back to me. I can confirm it is only partially loading the TablePress plugin:
```php
// TablePress support
if ( defined( 'TABLEPRESS_ABSPATH' ) ) {
    $tp_controller = TablePress::load_controller( 'frontend' );
    $tp_controller->init_shortcodes();
}
```
I will reach out to the plugin author and let them know.

Thanks again!

**Comment by TobiasBg** [comment]
Hi,

great! Thanks for checking this!

Best wishes,
Tobias
