### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by archon810** [TobiasBg/TablePress#124]
Hi,

Please see this https://github.com/westonruter/amp-tablepress (@westonruter is one of the core AMP and AMP WP contributors) and this https://github.com/westonruter/amp-tablepress/issues/1.

Any chance we can see AMP support in the plugin natively?

Thanks.

**Comment by westonruter** [comment]
The dependency here is on the data table library supporting a server-side rendered UI, and for all the library JS code to be under 150KB (much smaller ideally, as this is the limit/budget AMP imposes for all `amp-script` JS on a page). I do not believe jQuery DataTables is a good fit for either of these constraints:

1. The jQuery DataTables library is >80KB in addition to jQuery itself being >80KB, so these alone will be over the 150KB budget. 
2. Additionally, I don't see that jQuery DataTables is able to hydrate a server-rendered data table UI.

I will note that if these constraints were implemented in TablePress, it would not only be a benefit for AMP support: it would improve the performance of TablePress on non-AMP pages. It is always good for less script to be sent to the browser and for DOM mutations to be deferred until user gestures happen. AMP support would be an additional benefit.

**Comment by TobiasBg** [comment]
Hi @archon810,

thanks for this suggestion, and thanks @westonruter for the work on this and the detailed advice! I really appreciate it!

While it would be great to have this, I agree the AMP constraints make this pretty much impossible right now, as the DataTables jQuery library is a fundamental feature for most TablePress users. Replacing it with a smaller library, preferably even React-driven and with UI being pre-renderable on the server, would be nice, but are not doable for me at this time.

I therefore recommend using Weston's plugin for sites that need AMP support for TablePress tables (with the JS features enabled).

I'll go ahead and close this as "maybelater" for the time being. Of course, this can always be revisited if conditions or prerequisites change!
