### ISSUE TITLE
Adding background color for single cells

### ISSUE THREAD

**Issue by Zodiac1978** [TobiasBg/TablePress#125]
Hi Tobias,

I want to add something like #41 to TablePress to make it more useful for my usecase.

I'm creating courses for fitness center a lot and we are using TablePress in some cases, because it is a very flexible approach. But it would be great to add a background color for single cells.

Here is an example: https://bit.ly/2MAMulp

I don't see this as a feature for TablePress itself, but I'm wondering if it is possible to add some UI to every single cell as an extension.

I don't find any filter or action hooks for this and not in the edit area too. Can you help me to find it (if available) or do you consider adding a filter or action hook to make this possible?

**Comment by TobiasBg** [comment]
Hi @Zodiac1978,

For this, you could look into using the TablePress Cell Highlighting Extension from https://tablepress.org/download/extension/tablepress-cell-highlighting.zip . For some examples, please see https://wordpress.org/support/topic/tablepress-conditional-colours-in-cells/ For more, please also see the PHP file source code, which has an example in the comment at the top.

As you probably want to format the same course (names) in the same background color, this should be the most flexible/automatic solution. Besides the course names, you could of course also use custom keywords (probably hidden via a hidden `<span>` or similar).

Regards,
Tobias

**Comment by Zodiac1978** [comment]
Hi @TobiasBg ,

I've read the other threads on Github and the forums I am aware of this solution. But the owner of those fitness center sometimes want to maintain this on their own. And I'm unsure if this "adding another term to the shortcode" is easy enough for them. A UI with a color picker direct below the cell would be great. I just need some actions/filter to get this done, I think as there are none on those places at the moment.

Thanks for considering and a Happy New Year!

All the best,
Torsten

**Comment by TobiasBg** [comment]
Hi @Zodiac1978,

indeed, there are no real filters on the "Edit" screen that would adding such UI. The reason basically is that these would not yet be sufficient. After all, the chosen values would have to be saved somehow as well. This would mean that either the internal data format for tables is adjusted or that the color values are stored elsewhere. Both ways would also require that the JavaScript code for the "Edit" screen (with saving and everything is modified). I just don't see how that could be possible with filter or action hooks though :-(

Adding the plain color pickers should also be possible with JavaScript code, I think, but the main problem of how and where to save the color information remains...

Could another trick be to set the padding in the table cells to 0 and add a custom wrapper `<div>` or `<span>` inside the table cells? Then, you could directly add the background color (and padding) to that, similar to your current solution?

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

at this time, I don't see a feasible way to integrate something like this. If specific ideas or code approaches come up, we can certainly revisit this!

Thanks,
Tobias

**Comment by Zodiac1978** [comment]
Thanks for your thoughts about it! I agree that this is not easy to implement with the current infrastructure. Maybe I see another idea how to achieve this ...
