### ISSUE TITLE
TablePress responsive tables not working

### ISSUE THREAD

**Issue by intochzcom2** [TobiasBg/TablePress#127]
Hi i have a problem TablePress  not working well on my web with mobile view can any one help me to sort out this for more you can check the issue [click here](https://bestpropanegrill2020.com/) .

**Comment by TobiasBg** [comment]
Hi @intochzcom2,

thanks for your post, and sorry for the trouble.
Please take a look at the possible solution from https://tablepress.org/extensions/responsive-tables/

Regards,
Tobias
