### ISSUE TITLE
Tailwind and/or generic support for utility css-frameworks

### ISSUE THREAD

**Issue by chrona** [TobiasBg/TablePress#129]
Would it be possible to change or remove the validation-check for custom css-classes?

Currently it checks for `[A-Za-z0-9- _]*` which makes it impossible to add classes from utility frameworks like [tailwind](https://tailwindcss.com/), for example `class="md:max-w-md md:mx-auto"`.

**Comment by TobiasBg** [comment]
Hi @chrona,

I did some quick reading, and most sites say that the `:` is not really allowed in CSS classes, and should be escaped then. But I guess that tailwind properly does that in its CSS...
So, there's no real drawback to allow the `:` in "Extra CSS classes". Are other characters also needed?

I think that I can make this change for the upcoming release of TablePress 1.11, once WordPress 5.4 ships next week.

Regards,
Tobias

**Comment by chrona** [comment]
Sorry for the late reply! Basically you're right, it's technically not allowed, but I guess that's how frameworks go nowadays 🤷‍♂️

Thanks a lot for adding this!
