### ISSUE TITLE
Disable highlighting hovered rows

### ISSUE THREAD

**Issue by svenalbinus** [TobiasBg/TablePress#130]
Hi,

I know, with this snippet:

`.tablepress .row-hover tr:hover td {
  background-color: #ff0000;
  color: #00ff00;
}`

I can change the color and the background of a hovered row. But I have also some little tables for instance with only 5 or 6 rows, so this feature make no sense.

How can I disable it completely?

I tried thinks like:

`background-color: transparent;` or `background: none;` both with and without `!important;` but nothing works.

Thx in advance for any help.

Best
Sven

**Comment by TobiasBg** [comment]
Hi @svenalbinus,

have you seen that you can simply turn that feature off on a per-table basis via the corresponding checkbox on the table's "Edit" screen?

Regards,
Tobias

**Comment by svenalbinus** [comment]
Hi Tobias,

omg, sometimes it is impossible to see the forest for the trees :-)

Many thx!

Best
Sven
