### ISSUE TITLE
class 'TablePress' does not have a method 'sanitize_css_class' 

### ISSUE THREAD

**Issue by SteveCruz** [TobiasBg/TablePress#132]
Hello Tobias,

First of all, thanks a lot for your useful plugin!
After the update today, I received an error on my website:

`Warning: array_map() expects parameter 1 to be a valid callback, class 'TablePress' does not have a method 'sanitize_css_class' in xxx/wp-content/plugins/tablepress/classes/class-render.php on line 479`

I simply fixed it temporarily by commenting out the line in the plugin. I guess the input in line 479 is wrong, but i am not too familiar with php.

`$css_classes = array_map( array( 'TablePress', 'sanitize_css_class' ), $css_classes );`

Let me know if you need further details.

Best wishes,
Steve

**Comment by TobiasBg** [comment]
Hi @SteveCruz,

that's strange... That method exists at https://github.com/TobiasBg/TablePress/blob/master/classes/class-tablepress.php#L383
Also, I haven't received other such reports, even though the update was already downloaded more than 20,000 times today.

My guess therefore is that the update didn't run through completely, on your site, and that your file `class-tablepress.php` maybe still is from a previous version.

Can you maybe (manually) reinstall TablePress from a fresh download?

Regards,
Tobias

**Comment by SteveCruz** [comment]
Hi @TobiasBg,

It is working now. It was installed correctly (I did a diff with a newly downloaded one), but it seems that the old version was still somehow partially in the cache.  
Sorry for the inconvenience and thanks for the prompt reply. 

Best regards,
Steve

**Comment by TobiasBg** [comment]
Hi,

great! Thanks for the confirmation!

Best wishes,
Tobias
