### ISSUE TITLE
lang-mn.json fix

### ISSUE THREAD

**Issue by tnerguiTT** [TobiasBg/TablePress#134]
Translation below is accurate and tested as Datatables one somehow didn't work. 
{
	"emptyTable":		"Хүснэгт хоосон байна",
	"info":				"Нийт _TOTAL_ бичлэгээс _START_ - _END_ харуулж байна",
	"infoEmpty":		"Тохирох үр дүн алга",
	"infoFiltered":		"(нийт _MAX_ бичлэгээс шүүв)",
	"infoPostFix":		"",
	"lengthMenu":		"Дэлгэцэд _MENU_ бичлэг харуулна",
	"loadingRecords":	"Ачааллаж байна...",
	"processing":		"Боловсруулж байна...",
	"search":			"Хайлт:",
	"zeroRecords":		"Тохирох бичлэг олдсонгүй",
	"paginate": {
		"first":		"Эхнийх",
		"previous":		"Өмнөх",
		"next":			"Дараах",
		"last":			"Сүүлийнх"
	},
	"aria": {
		"sortAscending":	": цагаан толгойн дарааллаар эрэмбэлэх",
		"sortDescending":	": цагаан толгойн эсрэг дарааллаар эрэмбэлэх"
	},
	"decimal":			"",
	"thousands":		","
}

**Comment by TobiasBg** [comment]
Hi @tnerguiTT,

ah, we worked on the same simultaneously...
Can you please try the version I just pushed?

Regards,
Tobias

**Comment by tnerguiTT** [comment]
Will do. 
But there is little error in the translation:

		"next":			"Өмнөх",
		"previous":		"Дараах"

needs to be changed to:

"next": "Дараах",
"previous": "Өмнөх",

**Comment by TobiasBg** [comment]
Thanks! I also fixed and pushed that now :-)

**Comment by tnerguiTT** [comment]
Thanks, Tobias.
