### ISSUE TITLE
TablePress Responsive Tables in WordPress

### ISSUE THREAD

**Issue by BSCShoes** [TobiasBg/TablePress#135]
Hello, I have one problem TablePress and Tables are displayed incorrectly on mobile view. [Check page](https://bestshoeschoice.com/best-athletic-shoes-for-nurses/) with the mobile view & let me know best solution for that. i am using generatepress theme on my website.

**Comment by TobiasBg** [comment]
Hi @BSCShoes,

for some ideas for making a table responsive, please see https://tablepress.org/extensions/responsive-tables/

Regards,
Tobias
