### ISSUE TITLE
[enhancement] Hook for WordPress post id instead of table id when saving?

### ISSUE THREAD

**Issue by MewingLullaby** [TobiasBg/TablePress#137]
Hi 

I've run into a roadblock where I'm trying to get the WordPress post id of a table and through searching the plugin and docs I've found a tablepress_event_saved_table hook, however this only returns the table id and not the post it's associated with.

What are your thoughts about adding something like this? Or the rationale on why it would be a bad idea.

If you're wondering why someone would need this functionality it's to allow my secretary to do simple input (which the plugin is a godsend for thank you) that can then be used for more complicated processes under the hood. 

If this is the wrong way to use this hook or you know another please let me know!

**Comment by TobiasBg** [comment]
Hi @MewingLullaby,

I'm not sure that I understand. You are looking for the post ID of the internal data store (Custom Post Type) of a TablePress table? What are you then trying to achieve with that data (JSON format)?

I think it might be better to use the table ID to then load the table again and use the "normal" data (a two-dimensional PHP array).

Regards,
Tobias

**Comment by MewingLullaby** [comment]
Yes that's what I was asking the Custom Post Type ID.
However after trying your tip about loading the table it does the job I was looking for!
Thanks for your insight it's very appreciated
