### ISSUE TITLE
Changes to Table Not Showing Up on Site

### ISSUE THREAD

**Issue by stacieisms** [TobiasBg/TablePress#138]
Hello:  I've made changes to a table in tablepress that I can see in the preview, but they aren't showing when the site is live.  Not sure why.

**Comment by TobiasBg** [comment]
Hi @stacieisms,

on the page where you are showing the table, can you please check if you are still seeing the table's Shortcode (something like `[table id=123 /]`? There are some themes that seem to replace this with static HTML code, when features like frontend editing are used.

Regards,
Tobias

**Comment by stacieisms** [comment]
I'm not a programmer, I'm very new to this.

**Comment by TobiasBg** [comment]
Hi @stacieisms,

ok, that's good! Can you please check again after changing that Shortcode to
`[table id=1 responsive=scroll cache_table_output=false /]`
?

Regards,
Tobias
