### ISSUE TITLE
Support for importing with semi-colon separated values

### ISSUE THREAD

**Issue by tifDev** [TobiasBg/TablePress#139]
Hello,

Please add an option in the dropdown to import semi-colon separated values. I see that this is possible on table export but not on table import.

Congratulations for your plugin.

**Comment by TobiasBg** [comment]
Hi @tifDev,

the CSV importer normally recognizes the used separator character automatically, so that no selection should be necessary.
Can you maybe share the CSV file that you are having problems with?

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

as you have also posted about this at https://wordpress.org/support/topic/support-for-importing-with-semi-colon-separated-values-2/, let's continue the discussion there, until there's a clear actionable item for TablePress code changes.

Best wishes,
Tobias
