### ISSUE TITLE
Table shows Right to Left 

### ISSUE THREAD

**Issue by aurangzebkhan-com** [TobiasBg/TablePress#141]
I am a beginner and a teacher of English. I use tables showing English words/synonyms and meanings in Urdu. The problem is that my table goes right to left. Whereas I want it from Left to Right and text-align also left.
Here is a link how my table looks.
https://www.aurangzebkhan.com/2020/10/13/table-press-experiment/

**Comment by TobiasBg** [comment]
Hi @aurangzebkhan-com,

that's because your site's language is set to an RTL language.
To change the direction of the table, you'd need to add this to the "Custom CSS" textarea on the "Plugin Options" screen of TablePress:
```CSS
.dataTables_wrapper,
.tablepress {
	direction: ltr;
}
```
Regards,
Tobias
