### ISSUE TITLE
Special html characters are not escaped

### ISSUE THREAD

**Issue by peremenov** [TobiasBg/TablePress#142]
### Issue:
Special html characters are not escaped in the table output

### Steps to reproduce:
* Put `<` or `>` characters to the table cell in editor section
* Check the source code of the corresponding page on the front-end

#### Expected
Characters are escaped in the table cells `&lt;`, `&gt;`

#### Actual
Characters printed as it is (not escaped)

**Comment by TobiasBg** [comment]
Hi @peremenov,

I see what you mean, but this is expected. Otherwise, it would not be possible to use HTML code in the table cells.

if you want to show `<` and `>` in the table, you will need to write them as escaped entities, i.e. `&lt;` and `&gt;`.

Regards,
Tobias

**Comment by peremenov** [comment]
I see. IMO this is potentially dangerous, because user can make a mistake. Also in documentation there is no mention (or I couldn't find it) of this feature.

**Comment by TobiasBg** [comment]
Hi,

you are right, this is not really documented at this time. I hope to be able to improve on that.

But can you explain why this could be dangerous?

Regards,
Tobias

**Comment by peremenov** [comment]
The user can accidentally break the layout of his page, if unintentionally (not) close the tag.

**Comment by TobiasBg** [comment]
Hi,

ah, that's what you mean. Yes, that's true. But they should likely notice that quickly.

Unfortunately, I don't know a way to handle this better :-(

Regards,
Tobias
