### ISSUE TITLE
Add extension

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#143]
@TobiasBg: The TablePress plugin website lists [extensions](https://tablepress.org/extensions/) for TablePress:
[TablePress Rowspan All](https://github.com/strarsis/tablepress-rowspan-all) which allows to use `#rowspan#` in table headers.
It could be useful for TablePress users to find that extension listed on the site.

**Comment by TobiasBg** [comment]
Hi @strarsis,

thanks for your contribution here! At this time, I don't have plans to list available third-party Extensions on that documentation page, mainly as it would be too confusing for users on where to get them, etc. or who is supporting them.
I'll however definitely keep your idea in mind and will guide interested users to your Extension!

Thanks for your work on this!

Regards,
Tobias
