### ISSUE TITLE
Accessibility - Sorting 

### ISSUE THREAD

**Issue by timothyshambra** [TobiasBg/TablePress#147]
TablePress appends a string to the table header's aria-label (: activate to sort column ascending) which then does not match the text inside the header.

https://www.w3.org/TR/WCAG/#label-in-name
https://tablepress.org/extensions/change-datatables-strings/

**Comment by TobiasBg** [comment]
Hi @timothyshambra,

thanks for your feedback!

These labels are added by the external DataTables JS library, see https://datatables.net/reference/option/language.aria.sortAscending

Now, I'm not too familiar with ARIA labels, but from what I understand, the idea of this particular one is to inform the user about the possibility of sorting, e.g. via a screen reader when she can't see the sorting arrows.
That's the reason why there's the extra text after the header cell text.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @timothyshambra,

did you already have a chance to review my last reply?
Without further feedback, I'm not sure that a change is really needed here.

Best wishes,
Tobias

**Comment by TobiasBg** [comment]
Hi,

at this time, I don't see an actionable item here. Please feel free to reopen the ticket with more details and feedback. Thanks!

Best wishes,
Tobias
