### ISSUE TITLE
Add original post ID to `column_cb`

### ISSUE THREAD

**Issue by matzeeable** [TobiasBg/TablePress#148]
Hey!

Here is Matthew, the developer of Real Category Management (https://wordpress.org/plugins/real-category-library-lite/) and we are doing a big rewrite of the plugin. For the rewrite, we want to make the plugin compatible with TablePress. We have currently implemented some integration code to make it work.

![image](https://user-images.githubusercontent.com/1008534/110809648-631c6a80-8285-11eb-9959-101e9aab6409.png)

Unfortunately, the drag & drop does currently not work cause TablePress is using an internal mapping of `table_id` to `wp_posts.ID`. Is there any chance to add something like `data-post-id="%d"` attribute to the `<input type="checkbox"` HTML tag:

https://github.com/TobiasBg/TablePress/blob/fedddc5243f0d3926211f7534e68e253a83d9ed8/views/view-list.php#L385-L389

Regards
Matthew 😊

**Comment by TobiasBg** [comment]
Hi @matzeeable,

that's actually not that trivial, as the post ID is "masked" behind the internal table APIs. In fact, the "List of tables" screen does not even "know" that the tables are stored as WordPress posts (and technically, they don't have to be).

Can you maybe explain why you need the post IDs here? Can't you use the table IDs? This would also be safer and future-proof, e.g. when the connection between table ID and post ID is changed (in the background).

Or could you maybe solve this without needing a change in TablePress by using a custom copy of the [_get_post_id](https://github.com/TobiasBg/TablePress/blob/master/models/model-table.php#L765) method?

Best wishes,
Tobias

**Comment by matzeeable** [comment]
Hi again @TobiasBg !

Thanks for your message.

I need the post ID, so I can move the post to a category via [`wp_set_object_terms`](https://developer.wordpress.org/reference/functions/wp_set_object_terms/).

> Or could you maybe solve this without needing a change in TablePress by using a custom copy of the _get_post_id method?

I think this could solve the issue, yes. But this API is currently not public.

Regards,
Matthew 😊

**Comment by TobiasBg** [comment]
Hi @matzeeable,

>  But this API is currently not public.

That's why I meant "custom copy" :-) That `_get_post_id` method essentially just calls one other method - which is public :-)

For me, this would be the preferred way of handling this.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @matzeeable,

did this approach work for you?

Regards,
Tobias

**Comment by matzeeable** [comment]
Hey @TobiasBg !

Thanks for your follow-up.

Currently, we had no more time to address this issue. If you like, you can currently close this ticket, as we have this issue in our issue tracker - and reopen as needed.

Regards,
Matthew 😊

**Comment by TobiasBg** [comment]
Hi @matzeeable,

sounds good to me! Please let know about any progress in the future.

Best wishes,
Tobias
