### ISSUE TITLE
Replace jQuery.ready with window.onload

### ISSUE THREAD

**Issue by Tumas2** [TobiasBg/TablePress#149]
Hey there!

We recently put a ``defer`` on __jQuery__ and any other script needing it.
However we noticed the TablePress plugin adds inline JS in the footer which uses ``jQuery(document).ready``

Since __jQuery__ does _not_ load in time the inline script fails, however when we use ``window.onload`` it works, example:
```javascript
window.onload = function() {
    jQuery('#tablepress-67').dataTable({"stripeClasses":["even","odd"],"ordering":false,"paging":false,"searching":false,"info":false});
};
```
Is there a possibility to add this as an option (or replace it with ``window.onload``) in a future update?

**Comment by TobiasBg** [comment]
Hi @Tumas2,

thanks for this suggestion! While this approach does look interesting, I'm not sure that I can implement this as a default for TablePress at this time. There's just too many possibilities where this could break or potentially could cause issues with backward compatibility.
I will however investigate a possibility that would allow to change this by using a plugin filter hook!

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @Tumas2,

I did add support for a plugin filter hook now, in 34a86c2f43488c3f1182df0f6176973fc3d64a22.
You can filter `tablepress_all_datatables_commands_wrapper` to return the desired wrapper instead of jQuery.ready now!

Best wishes,
Tobias

**Comment by Tumas2** [comment]
Awesome, thank you!
