### ISSUE TITLE
Sorting issues with DD/MM/YYYY

### ISSUE THREAD

**Issue by emiliodallatorre** [TobiasBg/TablePress#152]
Hi,
I'm having issues in sorting a table by date (specifically, dates are sorted as if they are MM/DD/YYYY).

I already tried adding `"columnDefs": [ { "type": "date-eu", "targets": [ 0 ] } ]` to custom options.

My table is publicly available [here](https://www.lavoce.info/chi-ci-finanzia/).

**Comment by TobiasBg** [comment]
Hi @emiliodallatorre,

in order to use the `date-eu` data type, you must first download, install, and activate the TablePress Extension from https://tablepress.org/extensions/datatables-sorting-plugins/ as a new plugin on your site.

Regards,
Tobias

**Comment by emiliodallatorre** [comment]
> Hi @emiliodallatorre,
> 
> in order to use the `date-eu` data type, you must first download, install, and activate the TablePress Extension from https://tablepress.org/extensions/datatables-sorting-plugins/ as a new plugin on your site.
> 
> Regards,
> Tobias

You're completely right, I didn't install it.
Is there also a way to select a default sort for a table?

I'm sorry for the useless issue, I will close it ASAP!

**Comment by TobiasBg** [comment]
Hi @emiliodallatorre,

good to hear that this helped!
To sort by date when the table is loaded, you could extend your "Custom Command" to
`"columnDefs": [ { "type": "date-eu", "targets": [ 0 ] } ], "order": [ [ 0, "asc" ] ]`

Regards,
Tobias

**Comment by emiliodallatorre** [comment]
> Hi @emiliodallatorre,
> 
> good to hear that this helped!
> To sort by date when the table is loaded, you could extend your "Custom Command" to
> `"columnDefs": [ { "type": "date-eu", "targets": [ 0 ] } ], "order": [ [ 0, "asc" ] ]`
> 
> Regards,
> Tobias

I wonder that I can achieve reverse sorting by replacing `"asc"` with `"desc"` as in Firebase JS query?

**Comment by emiliodallatorre** [comment]
Hi @TobiasBg,
unfortunately I noticed that, after this configuration, table pagination stopped working...
It starts paginating again if I remove the "Custom Command".

**Comment by TobiasBg** [comment]
Hi @emiliodallatorre,

yes, you can of course also replace `"asc"` with `"desc"`. Please add the command again, so that I can investigate this in the page.

Regards,
Tobias

**Comment by emiliodallatorre** [comment]
Roger, @TobiasBg: command added.

**Comment by TobiasBg** [comment]
Hi @emiliodallatorre,

you removed the last `]` of your original "Custom Command". Please try again with (exactly)
`"columnDefs": [ { "type": "date-eu", "targets": [ 0 ] } ], "order": [ [ 0, "asc" ] ]`

Regards,
Tobias

**Comment by emiliodallatorre** [comment]
> Hi @emiliodallatorre,
> 
> you removed the last `]` of your original "Custom Command". Please try again with (exactly)
> `"columnDefs": [ { "type": "date-eu", "targets": [ 0 ] } ], "order": [ [ 0, "asc" ] ]`
> 
> Regards,
> Tobias

I can confirm this is working, kindly thanks @TobiasBg.

**Comment by TobiasBg** [comment]
Hi @emiliodallatorre,

great! Thanks for the confirmation!

Best wishes,
Tobias
