### ISSUE TITLE
Responsive Table extension is triggering datatables

### ISSUE THREAD

**Issue by Zodiac1978** [TobiasBg/TablePress#159]
Hi @TobiasBg,

I've installed the Responsive Tables extension and if I use the `collapse` feature, the table is using the datatables JS (showing pagination/search, etc.), although this is disabled for the table.

Looks like a bug. Or am I doing something wrong here?

**Comment by TobiasBg** [comment]
Hi @Zodiac1978,

that's expected, as the `collapse` mode uses a DataTables extension: https://datatables.net/extensions/responsive/
For this, it's necessary to turn on DataTables. If you don't want the pagination, search, etc. features, you'd have to turn those checkboxes off individually.
(In hindsight, the "Use DataTables" checkbox should not exist, but I can't really remove it now...)

Best wishes,
Tobias

**Comment by Zodiac1978** [comment]
Makes sense! Thanks for your super fast response and the clarification 👍

You can close the issue then (or leave it open if you want to use this as a reminder to document this or do something else).
