### ISSUE TITLE
Cross site scripting

### ISSUE THREAD

**Issue by tanimdiucse123** [TobiasBg/TablePress#163]
Step 1: 
![image](https://user-images.githubusercontent.com/97121933/158077909-aa77e49b-194e-47d3-8391-64f141e7bbf7.png)

Step 2: 
![image](https://user-images.githubusercontent.com/97121933/158077930-67041f37-61ee-4cb0-83aa-d7f0b62f264b.png)

Step 3:
![image](https://user-images.githubusercontent.com/97121933/158077941-5d16436e-2c0b-47b1-8bc3-fa0a1651e797.png)

Step 4:
![image](https://user-images.githubusercontent.com/97121933/158077955-ab36c76a-a662-49aa-809e-7de64074c26f.png)

**Comment by tanimdiucse123** [comment]
![image](https://user-images.githubusercontent.com/97121933/158077975-b87033db-32e2-4ef1-a9a8-f836d2ef4741.png)

**Comment by TobiasBg** [comment]
Hi @tanimdiucse123,

thanks for your report, I really appreciate it!

According to your screenshots, you were logged-in as an Administrator when you submitted the payload.
Administrator and Editor users are permitted to submit unfiltered HTML and JavaScript. WordPress (and TablePress) allows them to do this. These users have the unfiltered_html capability, see https://wordpress.org/support/article/roles-and-capabilities/#unfiltered_html .
This is not a security vulnerability in the WordPress eco-system.
You can test this yourself by adding the following to your wp-config.php file, which disables this capability:
`define( 'DISALLOW_UNFILTERED_HTML', true );`
You will notice that with this constant set to true, that you will not be able to reproduce your issue.
You can read more about this at https://make.wordpress.org/core/handbook/testing/reporting-security-vulnerabilities/#why-are-some-users-allowed-to-post-unfiltered-html .

Best wishes,
Tobias
