### ISSUE TITLE
Table cross the maximum size of template

### ISSUE THREAD

**Issue by sunuilhamp** [TobiasBg/TablePress#165]
![Screenshot_2022-07-26-12-32-49-426_com android chrome](https://user-images.githubusercontent.com/31399188/180917712-8fb8837e-591c-4ebf-859f-2009564658b4.jpg)

**Comment by TobiasBg** [comment]
Hi @sunuilhamp,

this is the classical problem of responsiveness of tables on the web. Please see https://tablepress.org/extensions/responsive-tables/ for some approaches to deal with this.

Regards,
Tobias
