### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by vinnyparker** [TobiasBg/TablePress#174]
Hi Tobias! First of all, thank you for the amazing plugin! it helps me a lot.
So, with this new version, how can i translate the context menu?
I'm from brazil, and the context menu, is in english. Is there anyway to contribute with the translation to brazilian portuguese?

**Comment by TobiasBg** [comment]
Hi @vinnyparker,

thanks for wanting to translate TablePress! The plugin uses the WordPress.org translation system, at https://translate.wordpress.org/projects/wp-plugins/tablepress/
After your log in with a wordpress.org account there, you can start translating, and after a translation editor reviews the strings, they should automatically appear in the translation files.

Best wishes,
Tobias

**Comment by TobiasBg** [comment]
Hi @vinnyparker,

you are very welcome! Thanks again for your help with the translations, I really appreciate it!

Best wishes,
Tobias
