### ISSUE TITLE
Incorrect row hover highlighting with spanned cells in Extension 1.0

### ISSUE THREAD

**Issue by nmadhok** [TobiasBg/TablePress#32]
#### My table with ``rowspan``:
![0](https://cloud.githubusercontent.com/assets/3374962/6762584/a91af0f2-cf39-11e4-8489-f0d2ca32a812.png)

#### This works as desired:
![1](https://cloud.githubusercontent.com/assets/3374962/6762599/f54c7a36-cf39-11e4-85f5-73eeef124041.png)

#### This works as desired:
![2](https://cloud.githubusercontent.com/assets/3374962/6762600/fa093550-cf39-11e4-89f2-bb63f71a7349.png)

#### This doesn't work as expected. ``Michelle -> Google -> USA`` should have been highlighted:
![3](https://cloud.githubusercontent.com/assets/3374962/6762601/026abebc-cf3a-11e4-890b-df8acaa1f11f.png)

#### This doesn't work as expected. ``Sandy -> Google -> USA`` should have been highlighted:
![4](https://cloud.githubusercontent.com/assets/3374962/6762602/070512e2-cf3a-11e4-8c74-1f97e424c803.png)

@TobiasBg

**Comment by TobiasBg** [comment]
Hi @nmadhok,

thanks for reporting this! While the Extensions are not a priority for me a the moment, I'll definitely check this out as soon as I find some time.

Regards,
Tobias

**Comment by nmadhok** [comment]
@TobiasBg I will try to submit a PR for this in the meantime if I'm able to fix it. Can you tell me where I can find the code for this on GitHub in your repository?

**Comment by TobiasBg** [comment]
That would be great! I don't have the Extensions in a public repo here yet, but maybe you can send me the patched file?

**Comment by nmadhok** [comment]
@TobiasBg Sure. I will email you the patched file once I work upon it.

**Comment by TobiasBg** [comment]
The Extension is rarely used, as it has never been published really. I'll therefore deprecate it.

**Comment by kampiamodikuesto** [comment]
was the patch released in 2018?

**Comment by TobiasBg** [comment]
Hi @kampiamodikuesto,

what exactly do you mean here?

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

no, sorry, it hasn't. The Extension is officially deprecated and should not be used anymore.

Regards,
Tobias

**Comment by kampiamodikuesto** [comment]
so it is better to not use rowspan and colspan:) thanks

**Comment by TobiasBg** [comment]
Hi,

well, only if you really need the hover effect to look nice...

Best wishes,
Tobias
