### ISSUE TITLE
TablePress Custom CSS not being applied

### ISSUE THREAD

**Issue by ollly1363** [TobiasBg/TablePress#34]
Hi there,  I inputted custom CSS as described in a previously closed thread in order to align middle a table.  When saved the custom CSS made no change to the table.

Please advise.

Thanks in advance.

David

**Comment by TobiasBg** [comment]
Hi,

thanks for your post, and sorry for the trouble.

Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by ollly1363** [comment]
This is the code I tried:

.tablepress td,
.tablepress th {
  text-align: center;
  vertical-align: middle;
}

**Comment by ollly1363** [comment]
Hi Tobias, I'm a novice at WordPress.  I'll put the table on a sample page as I've been working on it only previewing on the actual page.  I'll do that now.

**Comment by ollly1363** [comment]
Here's a test page with the table in question,  I will re-apply the custom CSS now.

http://www.scalepreventionusa.com/792-2/ ‎

Thanks in advance.

**Comment by ollly1363** [comment]
I did the following as I don't want to text align center on all of my tables:

.tablepress td,
.tablepress th {
	vertical-align: middle;
}

**Comment by ollly1363** [comment]
I'd also like to make the table background #ffffff

**Comment by TobiasBg** [comment]
There are several issues here:

Please don't add extra table HTML into the cells (like that `<td valign="middle"></td>`.
Also, text (in the third column) should not be wrapped in `<h4>` tags. Those are for headings only.

To set the background color, just uncheck the "Alternating row colors" checkbox for the table.

To then vertically align the cell, please use this "Custom CSS":
`
.tablepress tbody td,
.tablepress thead th {
  vertical-align: middle;
}
`

**Comment by ollly1363** [comment]
Understood, thanks, it's great when you know how! The <td valign="middle"></td> was me experimenting to see if I could get that done.  I'm more familiar with html than anything else.  Regarding the <h4> tags I did that as I wanted to easily use that particular style,  what should I use as an alternative?

**Comment by ollly1363** [comment]
I don't know why that posted as bold?

**Comment by TobiasBg** [comment]
It posted as bold as you did not escape the `<h4>` tags. You can of course keep using those, but it might be better to assign the desired font style to the cells, in the same way as you assign the alignment.

**Comment by ollly1363** [comment]
OK great, thanks for your help Tobias

**Comment by ollly1363** [comment]
How about cell padding?

**Comment by TobiasBg** [comment]
Padding can be set e.g. like this:
```CSS
.tablepress tbody td,
.tablepress thead th {
  padding: 20px;
}
```

**Comment by ollly1363** [comment]
Thanks, and how do I limit this to one table so I don't mess up the other tables on the site?

**Comment by TobiasBg** [comment]
For that, you'd use the ID-based CSS selectors, see https://tablepress.org/faq/css-selectors/

**Comment by DXDWXIKI** [comment]
hi TobiasBg'
i also have this same issue. 
I just changed the font size of table by adding this CSS:

.tablepress tbody td {
	font-size: 15px;
}

But this code is working on Desktop, Not in Mobile.

**Comment by TobiasBg** [comment]
Hi @DXDWXIKI,

Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias
