### ISSUE TITLE
TablePress - fixing the plugin header banner

### ISSUE THREAD

**Issue by ramiy** [TobiasBg/TablePress#35]
Hi,

I finished the final strings translation to hebrew and noticed that your plugin page on hebrew local (https://he.wordpress.org/plugins/tablepress/) needs banner update.

I wrote a post about this issue – https://generatewp.com/how-to-improve-your-plugin-header-image/

To fix this UI glitch you need to create a new bidirectional header images for LTR and RTL view.

Rami Y.
GenerateWP.com

**Comment by TobiasBg** [comment]
Hi,

thanks for the info on this! I see what you mean. As this is not just something that concerns TablePress, wouldn't a more general and better idea be to try to get RTL support for header images on wordpress.org? This might be a good ticket on the meta Trac.

Regards,
Tobias

**Comment by ramiy** [comment]
Tobias,

We already have a ticket on the meta trac:

https://meta.trac.wordpress.org/ticket/757

**Comment by TobiasBg** [comment]
Hi,

great! That's good to see! There seems to be some activity in that ticket as well :-)
Personally, I'm in favor of the `-rtl` idea here, so I'll wait how that turns out, in order to not have to redo the work.

Regards,
Tobias

**Comment by ramiy** [comment]
Tobias,

It won't be resolved any time soon.

The TablePress header banner needs a simple adjustment, just align the logo to the center of the banner. It's an easy fix.

Rami Y.
GenerateWP.com

**Comment by TobiasBg** [comment]
Hi @ramiy,

looks like it is fixed now! :-)
https://wordpress.slack.com/archives/meta-i18n/p1446142833000286

I'll add a TablePress RTL banner image as soon as I find some time!

Best wishes,
Tobias

**Comment by TobiasBg** [comment]
Done! :-)
https://he.wordpress.org/plugins/tablepress/

**Comment by ramiy** [comment]
Looks great!!
