### ISSUE TITLE
TablePress content doesn't show up in search results

### ISSUE THREAD

**Issue by revxx14** [TobiasBg/TablePress#39]
I'm working on a site that uses TablePress, and it seems that content inside of a table isn't showing up in search results. For example, on [this page](http://utilitysolutionsinc.myweblinx.net/products/overhead-cutouts/) there's a table with a cell that says "USCO-003". Searching for that via the search bar at the top of the page does return a few results, but not the actual correct result (which would be the "Overhead Cutouts" page.

I'm guessing this is because it's using a shortcode to display the table. Is there a way to fix this?

**Comment by TobiasBg** [comment]
Hi,

thanks for your question, and sorry for the trouble.

I can confirm that the search integration is not working on your site, but unfortunately, I don't see why :-(

You are right with the assumption that content that is rendered by Shortcodes is not searched by default. To work around this, TablePress has its own [search integration](https://github.com/TobiasBg/TablePress/blob/master/controllers/controller-frontend.php#L835). This basically works by intercepting the search query, searching through all tables, and then extending the actual search to also search for Shortcodes that contain the search term.

Unfortunately, other plugins or the theme can sometimes disturb this process. Can you therefore please try again after temporarily deactivating all other plugins and after switchting to a WordPress default theme like Twenty Sixteen? That way, we can find what's causing this.

Regards,
Tobias

**Comment by revxx14** [comment]
Sure thing, I'll check it out Monday when I'm back in the office. Thanks much :)

**Comment by TobiasBg** [comment]
Did these ideas help, @revxx14?

**Comment by revxx14** [comment]
Sorry I never followed up on this! I was able to get it working with the following:

```
add_filter('relevanssi_content_to_index', 'rlv_table_check', 10, 2);
add_filter('relevanssi_excerpt_content', 'rlv_table_check', 10, 2);
function rlv_table_check($content, $post) {
    //$additional_content = get_field("additional_content", $post->ID);
    $additional_content = get_post_meta( $post->ID, 'additional_content', true );

    if ($additional_content) {
        $additional_content_expanded = do_shortcode($additional_content);
        $content .= " " . $additional_content_expanded;
    }

    return $content;
}
```

Not sure it's the most efficient way to do this (I should probably be filtering with regex for the shortcodes specifically), but it works.

**Comment by TobiasBg** [comment]
Hi,

ah, you were using another plugin that also integrates into the search :-) That explains things a bit. Good to hear that you found a solution!

Best wishes,
Tobias

**Comment by Robyn-VS** [comment]
Hi,

I'm having the same issue with the search function... JacobDB, did you add that snippet of code to your functions.php file? I'm a designer, not a developer and trying to make sure the website I'm building searches the Tablepress table conten for my client...

Thanks in advance for your help!
Robyn :)

**Comment by TobiasBg** [comment]
Hi @Robyn-VS,

are you having these issues on a "standard" site or are you maybe using a special search plugin on your site?

Best wishes,
Tobias

**Comment by JacobDB** [comment]
@Robyn-VS yea, that went in my functions.php. That particular snippet is for expanding shortcodes within a custom field, and adding the results to the [Relevannsi](https://wordpress.org/plugins/relevanssi/) indexing process.

**Comment by Robyn-VS** [comment]
Hi @TobiasBg, having these issues on the standard site, I'm not using a special search plugin... I am using it with woo commerce though, I've added tables in the product short descriptions.

And thanks @JacobDB - I'm happy to add the relevannsi plugin, if that will make it work! What kind of custom fields would that snippet check?

**Comment by TobiasBg** [comment]
Hi @Robyn-VS,

thanks for the details! This is a different issue then. You will basically have to find out how to make those "product short descriptions" searchable by WordPress. Depending on how they are stored internally, they might not even be searchable to begin with. Then, if they are searchable, you'd have to make them parse Shortcodes so that those are searched.
As this has shown to be tricky for regular posts and pages (for which TablePress offers native support), this will probably not be easy :-/ Checking out third-party search plugins might therefore be a better option.

Regards,
Tobias

**Comment by Robyn-VS** [comment]
Hi @TobiasBg,

I thought that might be the case :-/ if I find a solution, I'll let you know! Might try modifying @JacobDB 's snippet to include the product short descriptions... Although hopefully there's an easier solution out there for me! Thanks for your quick responses :)

**Comment by zhumakz** [comment]
Hey. I have a very large table and therefore a very long query processing. Loads the table on page and it is necessary to wait 5 - 7 seconds. Then everything works. How can I disable the loading of the entire table and only include the search?

**Comment by TobiasBg** [comment]
Hi @zhumakz,

I'm afraid that that is not possible at the moment. The search works with JavaScript and this means that all data has to be transferred to the browser before a search can be made :-(

Regards,
Tobias

**Comment by NidhinAS** [comment]
Hi,

I am using tablepress for my website. I have colored even row and odd row separately. But when I include the search option and reduce the row limit some table showing the color properly with proper row limit and search options but some table not showing the search option and colors for the row.

**Comment by TobiasBg** [comment]
Hi @NidhinAS,

Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @NidhinAS,

Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by NidhinAS** [comment]
Hi.. thank you for your attention... my site is not publicly available right now...  I have reduced table width in a page.....but search and pagination appears right side of table... search and pagination not aligned to the table width... if the table width is page size, it seems ok...

**Comment by NidhinAS** [comment]
Hi.. thank you for your attention... my site is not publicly available right now... I have reduced table width in a page.....but search and pagination appears right side of table... search and pagination not aligned to the table width... if the table width is page size, it seems ok...
![Untitled](https://user-images.githubusercontent.com/35590921/91523242-d548e580-e919-11ea-9792-75b6f95c050f.jpg)

**Comment by NidhinAS** [comment]
Hi.. thank you for your attention... my site is not publicly available right now... I have reduced table width in a page.....but search and pagination appears right side of table... search and pagination not aligned to the table width... if the table width is page size, it seems ok...
![Untitled](https://user-images.githubusercontent.com/35590921/91523342-1ccf7180-e91a-11ea-9609-c31926b1606c.jpg)

**Comment by TobiasBg** [comment]
Hi @NidhinAS,

ok, can you please add this to the "Custom CSS" textarea on the "Plugin Options" screen of TablePress:
```CSS
.dataTables_wrapper .tablepress {
  width: 100% !important;
}
```
Regards,
Tobias

**Comment by NidhinAS** [comment]
thank you for your immediate reply.... i have to keep the table always 100% width.....if the table width reduced....search and pagination not compacted to the table width...

**Comment by TobiasBg** [comment]
Hi @NidhinAS,

so you actually want a smaller width? And not 100%? Then, you'd have to reduce the width of the container, like
```CSS
#tablepress-123_wrapper {
   width: 500px; 
}
```
Regards,
Tobias

**Comment by NidhinAS** [comment]
thank you @TobiasBg ....its workiing..... thank you
