### ISSUE TITLE
CSV export, UTF-8

### ISSUE THREAD

**Issue by olavxxx** [TobiasBg/TablePress#4]
Hello,

Inside TablePress / controllers / controller-admin.php , I had to add byte order mark to the CSV-export, to make it open successfully in Excel, without opening via the Data->Text (doubleclick to open)

This means:
$export_data = "\xEF\xBB\xBF" . $exporter->export_table( $table, $export['format'], $export['csv_delimiter'] );

AND

$download_data =  "\xEF\xBB\xBF" .  $export_data;

(just for the CSV exports, one for zip and one for non zipped).

**Comment by FireEmerald** [comment]
Just as a reference: This snippet adds the BOM for UTF8 in csv exported files via TablePress:
``` php
add_filter( 'tablepress_export_data', 'tablepress_add_bom_to_csv_exports', 10, 4 );

function tablepress_add_bom_to_csv_exports( $export_data, $table, $export_format, $csv_delimiter ) {
  if ( 'csv' === $export_format ) {
    $export_data = "\xEF\xBB\xBF" . $export_data;
  }
  return $export_data;
}
```
Source: https://wordpress.org/support/topic/umlaute-special-characters-in-export-files/#post-10348464
