### ISSUE TITLE
Multiple tbody tags in one table

### ISSUE THREAD

**Issue by alexander-heimbuch** [TobiasBg/TablePress#40]
I'm currently working on a TablePress plugin to joining multiple rows into categories. The HTML table standard supports this behaviour with multiple ``tbody`` tags. Digging deeper into the code I doesn't see any possibility to group rows, e.g. using an array of arrays as the ``data`` field for rendering.

I would really like to extend the class function towards such functionality but aren't sure if this possibly could find a way in the master.

**Comment by TobiasBg** [comment]
Hi @alexander-heimbuch,

thanks for your question, I really appreciate your efforts here!

I don't really think that this is something that is beneficial or useful for the majority of plugin users, and I can foresee many problems all over the place, for example when such a table is to be edited or when the JS features of the DataTables JS library are used. Those require a single `<tbody` from what I know.
I therefore don't really think that this is something that can be integrated into the actual plugin, but it's more something for a custom render class that you use only in your project.

Now, I'm not sure what "joining into categories" exactly means for you, but the TablePress Extension that is mentioned in https://wordpress.org/support/topic/group-by-column?replies=4#post-4473284 could maybe be a solution, ift this is about visually grouping rows. 

Regards,
Tobias

**Comment by alexander-heimbuch** [comment]
Hey @TobiasBg ,

thanks for the extensive answer, you gave a good hint wit ``DataTables``. I created a small plugin that uses DataTables to reorder the rows in multiple table bodies. Works quite well so far :)

https://github.com/alexander-heimbuch/tablepress-category

**Comment by TobiasBg** [comment]
Hi @alexander-heimbuch,

nice work! Looks good on first glance!

Best wishes,
Tobias
