### ISSUE TITLE
JS options are grayed out

### ISSUE THREAD

**Issue by oliverwh** [TobiasBg/TablePress#42]
Unable to uncheck JS options in settings.

Seems, there is a wrong "disabled" tag on fields. 

If somebody will have same issue - it can be also removed via developer tools/firebug directly in page code ^^

**Comment by TobiasBg** [comment]
Hi,

the JS options are greyed out if either the "Use DataTables" checkbox or the "Table Head Row" checkbox are unchecked, as those are requirements for the other settings.
Could that be the case here?

Regards,
Tobias

**Comment by oliverwh** [comment]
Hi, 
Yeah, I remember it was previously like so, however
Use DataTables is also grayed out.

**Comment by TobiasBg** [comment]
Hi,

Yes, that's greyed out if "Table Head Row" is unchecked, as the DataTables JS library requires a table header row.

Regards,
Tobias

**Comment by oliverwh** [comment]
Lol, really, sorry for disturbing :)
