### ISSUE TITLE
Authenticated Stored XSS

### ISSUE THREAD

**Issue by arall** [TobiasBg/TablePress#45]
Table fields data is not escaped when previewing tables. Authenticated users can trigger a Cross Site Scripting vulnerability.
However, the attack vector has a very low risk.

![image](https://cloud.githubusercontent.com/assets/1453137/15177201/3c8bb758-176f-11e6-94f0-aa40cd34cc03.png)

**Comment by TobiasBg** [comment]
Hi @arall,

thanks for your report! Can you please provide some more details here? What user role is the user that you tried this with?
Can you maybe send me an example, via email (the address is in the main plugin file "tablepress.php")?

Thanks a lot, I really appreciate your help!
Tobias
