### ISSUE TITLE
Fix table header in WP-Admin?

### ISSUE THREAD

**Issue by orschiro** [TobiasBg/TablePress#46]
Dear @TobiasBg,

Would it be possible to fix the table header in the WP-Admin?

Especially for long tables I always have to scroll back up to the top to remind myself which column stands for what.

Example of a header:
![image](https://cloud.githubusercontent.com/assets/170947/16176126/d645d892-3605-11e6-9d4b-f47c3e4b2270.png)

What do you think?

Thankfully,

~Robert

**Comment by TobiasBg** [comment]
Hi @orschiro,

thanks for the suggestion! Unfortunately, something like this is not yet possible at the moment, but it's definitely on my list of ideas for an upcoming redesign of the "Edit" screen!

Best wishes,
Tobias

**Comment by orschiro** [comment]
Hi Tobias, 

You're very welcome!

It's great to see what you're doing with Table Press and I really look forward to any feature that is getting closer to my request. :-)

Keep me updated!

Warmly,

~Robert
