### ISSUE TITLE
Question: Cell attributes with thead cell value

### ISSUE THREAD

**Issue by GaryJones** [TobiasBg/TablePress#47]
Imagine a simple table with the following markup:

```
<table>
	<thead>
		<tr>
			<th>Heading 1</th>
			<th>Heading 2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>A</th>
			<td>B</td>
		</tr>
		<tr>
			<th>C</th>
			<td>D</td>
		</tr>
	</tbody>
</table>
```

For the purposes of showing the table nicely on mobile, we'd like to add a `data-label` attribute to each body cell, with the value of the corresponding column header. The output should be like:

```
<table>
	<thead>
		<tr>
			<th>Heading 1</th>
			<th>Heading 2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th data-label="Heading 1">A</th>
			<td data-label="Heading 2">B</td>
		</tr>
		<tr>
			<th data-label="Heading 1">C</th>
			<td data-label="Heading 2">D</td>
		</tr>
	</tbody>
</table>
```

We think we'd need the  [`tablepress_cell_tag_attributes`](https://github.com/TobiasBg/TablePress/blob/31e0f15d2dff4950f1531baa91c7378a81698531/classes/class-render.php#L671) filter, and can see a table ID is available, but not sure how to go about limiting the filter to the right cells, and grabbing the right column header for the `data-label` value.

Could you offer a suggestion for the callback please?

cc @craigsimps

**Comment by TobiasBg** [comment]
Hi Garry,

yes, the `tablepress_cell_tag_attributes` filter hook is probably the best way to go here. It get's passed the table ID and column number as parameters, so with that, you could pick the desired table header content from a variable.

Regards,
Tobias

**Comment by GaryJones** [comment]
But, given the table ID, how would one go about getting the table header values?

**Comment by TobiasBg** [comment]
Hi Gary,

you'd simply load the table, like
`
$table = TablePress::$model_table->load( $table_id );
$header_row = $table['data'][0];
$label = $header_row[ $column_number - 1 ];
`
You should however cache the table (or just the header row) array, to safe on JSON decoding calls, e.g. by loading the data before adding the filter hooks.

Regards,
Tobias

**Comment by GaryJones** [comment]
@craigsimps Does this give you enough to go on?

**Comment by craigsimps** [comment]
@GaryJones Yes I should be able to work up a solution using the filter mentioned. Thanks for your help @TobiasBg
