### ISSUE TITLE
PHP 7 Compatibility based on PHP Compatibility Checker

### ISSUE THREAD

**Issue by phauer** [TobiasBg/TablePress#48]
Hi everyone,

I investigated whether my wordpress installation is ready for PHP7. That's why I used the Plugin [PHP Compatibility Checker](https://wordpress.org/plugins/php-compatibility-checker/) which checks my plugins for PHP7-compatibility.

It says that TablePress is not compatible due to the following 2 errors and 2 warnings:

```
FILE: /www/htdocs/w00d0b91/blog/wordpress/wp-content/plugins/tablepress/views/view-about.php
-------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------------------------------------------------
 185 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and deprecated since PHP 5.6 and removed since PHP 7.0 - use mysqli instead.
 186 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and deprecated since PHP 5.6 and removed since PHP 7.0 - use mysqli instead.
-------------------------------------------------------------------------------------------------------------------------------------------


FILE: /www/htdocs/w00d0b91/blog/wordpress/wp-content/plugins/tablepress/libraries/simplexlsx.class.php
------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------
 602 | WARNING | The use of function dl is discouraged from PHP version 5.3
 604 | WARNING | The use of function dl is discouraged from PHP version 5.3
------------------------------------------------------------------------------------------------------
```
I'm not a PHP expert, but the errors just revolves around deprecated functionality, which still works.

Within my local php 7 test setup, the TablePress just works fine. It seems that this is not a critical problem.

Will this be fixed? Is this a blocker for my php7 migration? I suppose it's not.

I'm using TablePress Version 1.7.

**Comment by TobiasBg** [comment]
Hi @phauer,

thanks for your post! This is nothing to worry about. TablePress is fully compatible to PHP 7. For details on these warnings, please see https://wordpress.org/support/topic/tablepress-php-70-compatibility?replies=6

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @boospot,

these are indeed placed there for backward compatibility. As TablePress (just like WordPress) supports PHP back to version 5.2.23, these calls are still necessary. They are however only ever called on these old systems, not on newer versions of PHP.

Regards,
Tobias

**Comment by boospot** [comment]
Thanks for response @TobiasBg 

I appreciate it. and thanks for clarification as well.
