### ISSUE TITLE
Additional Options in Edit Screen

### ISSUE THREAD

**Issue by vralle** [TobiasBg/TablePress#50]
The idea was to add a metabox with the advanced settings in the edit screen.

```
add_meta_box(
    'vr_tablepress_metabox', // $id
    esc_html__('Additional Options'), // $title
    'vr_table_options',
    'tablepress_edit'
);

functions vr_table_options( array $data)
    {
        $options = $data['table']['options'];
?>
        <table class="tablepress-postbox-table fixed">
            <tbody>
                <tr>
                    <th class="column-1" scope="row"><?php esc_html_e('First Column is Header'); ?>:</th>
                    <td class="column-2"><label for="option-first-column-th"><input type="checkbox" id="option-first-column-th" name="table[options][first_column_th]" value="true"<?php checked($options['table_head']); ?> /> <?php esc_html_e('The first cell of the table row is header.'); ?></label></td>
                </tr>
            </tbody>
        </table>
<?php
    }
```

But this doesn't work when Screen 'tablepress_edit'. Any way to add additional metabox to Edit Screen?

**Comment by TobiasBg** [comment]
Hi,

I'm afraid that this will not really work. Even if you were getting the advanced options to be visible, TablePress would not save them.

Regards,
Tobias

**Comment by vralle** [comment]
Hi, Tobias!

There is any way to expand the options ui?

**Comment by TobiasBg** [comment]
Hi,

while it should be possible to add custom meta boxes (I don't have the code available right now, but it should not be too difficult), the problem will be the saving of the options. That's not extendable at the moment :-(

Your best chance therefore is to add your options via Shortcode parameters, which can be configured much easier.

Regards,
Tobias
