### ISSUE TITLE
The table header does not fit to the table 

### ISSUE THREAD

**Issue by athimannil** [TobiasBg/TablePress#52]
The table header does not fit to the table when using sorting 😒

![screen shot 2016-12-01 at 4 14 38 pm](https://cloud.githubusercontent.com/assets/4364227/20799201/bec0555e-b7e1-11e6-8fcd-9ae8d869edab.png)

**Comment by TobiasBg** [comment]
Hi @athimannil,

does updating TablePress to the master branch (which contains an updated version of the DataTables JS library) help?

If not, can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by athimannil** [comment]
Thanks for your quick response. The version seems to be the latest 

here you can check the issue http://demo.athimannil.com/table/

**Comment by TobiasBg** [comment]
Hi,

you are probably affected by an issue with the Horizontal Scrolling feature here. I recommend to uncheck that checkbox and instead try the `scroll` mode of the TablePress Extension from https://tablepress.org/extensions/responsive-tables/

Regards,
Tobias

**Comment by athimannil** [comment]
It is kinda working now, much appreciated for your quick help and solution 👏

**Comment by TobiasBg** [comment]
Hi,

great! That's good to hear!

Best wishes,
Tobias
