### ISSUE TITLE
is it possible to disable particular table header ?

### ISSUE THREAD

**Issue by athimannil** [TobiasBg/TablePress#53]
does it possible to disable particular table header ?

For example I don't want the sorting for the **#** header. Any idea about disabling first row table header item ?  http://demo.athimannil.com/table/

**Comment by TobiasBg** [comment]
Hi,

yes, this is possible using a "Custom Command" on the table's "Edit" field. For an example, please see https://wordpress.org/support/topic/sort-a-column-in-tablepress/#post-7226443

Also, please post such support questions in the WordPress forums at https://wordpress.org/support/plugin/tablepress/ in the future. I monitor these closely and would like to use GitHub issues for actual bugs only. Thanks!

Regards,
Tobias
