### ISSUE TITLE
Any plans for wp-cli integration

### ISSUE THREAD

**Issue by Sher-Chowdhury** [TobiasBg/TablePress#54]
Hi,

I was just wondering if there are any plans to create wp-cli integration:

https://wp-cli.org/docs/tools/

This is so that I could import/export/create/delete tables from the bash command line to help me perform backups. 

Kind regards,
Sher

**Comment by TobiasBg** [comment]
Hi @Sher-Chowdhury,

thanks for your suggestion! At this time, I don't have plans to create such a wp-cli integration. I simply don't have the time for it. I also think that this wouldn't be that useful (yet) for the majority of TablePress users.
If someone else wants to step up and develop this, I'd gladly try to assist where possible!

At least for backing up, it should be sufficient to backup the relevant entries from the `wp_posts` database tables (the Custom Post Type is `tablepress_table`) and the `tablepress_tables` and `tablepress_options` entries from the `wp_options` database tables.

Regards,
Tobias

**Comment by RhettPrichard** [comment]
I was curious as to what the plugin's admin all tables tab is using to find a post of the post_type tablepress_table? I have been playing around with adding a post with the wp cli using the --post_type=tablepress_table arg, I have created a complete duplicate of a working table, and even custom edited the TablePress_tables option parameter to match, but it is not "enough" for the TablePress all tables admin tab to see it. I was wondering if there is some setting/meta/option I am missing that needs to be set to make it seen by the plugins all tables tab?
Thank you for you time.
Rhett

**Comment by TobiasBg** [comment]
Hi @RhettPrichard,

the table data is stored in `wp_posts`, with a `post_type` value of `tablepress_table`. In addition, the meta data is in `wp_postmeta`. Then, the post ID is mapped to a table ID in the `tablepress_tables` option in the `wp_options` DB table, which is where the "All Tables" screen gets its list from.

Regards,
Tobias

**Comment by RhettPrichard** [comment]
Thank you

**Comment by hadamlenz** [comment]
A possible idea for wp-cli support would be to change options for many tables all at once 

if you wanted to change a handfull of tables to show "The background colors of consecutive rows shall alternate"

```wp tablepress options option=alternate tables=1,2,3```
