### ISSUE TITLE
Allow more than one row in table header

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#55]
It would be nice if more than one row can be in the table header.

This is required for example in [nested table headers](https://jsfiddle.net/strarsis/qkgoeff2/) where 
multiple columns are grouped with sub-columns in second row.

Using `#rowspan#` for including rows below (e.g. the 2nd row) in table header wouldn't work, see
- https://github.com/TobiasBg/TablePress/blob/master/classes/class-export.php#L105
- https://github.com/TobiasBg/TablePress/blob/master/classes/class-render.php#L583

**Comment by TobiasBg** [comment]
Hi,

thanks for opening this issue! I see what you mean.
Unfortunately, I'll have to disappoint you here. This is not something that I have planned for TablePress at the moment.
I think that this would make the user interface and the integration of the DataTables JS library more tricky, and the rendering of the HTML code more difficult.

I'll therefore close this issue, to not raise false hopes. If someone wants to contribute such a feature, I'll gladly take another look, of course.

Best wishes,
Tobias

**Comment by strarsis** [comment]
@TobiasBg: I wrote an experimental plugin that also handles rowspan between thead + tbody to find out possible issues with them and everything works well. 
DataTables, also the release shipped with Tablepress plugin, 
already supports these ["Complex headers"](https://datatables.net/examples/basic_init/complex_header.html) including sorting, without any issues.

**Comment by TobiasBg** [comment]
Rowspan between `<thead>` and `<tbody>` cells? That sounds strange. Or do you mean rowspan between multiple `<tr>`s in the `<thead>`?
Is that experimental plugin available somewhere?

**Comment by strarsis** [comment]
@TobiasBg: The description "rowspan between thead and tbody" is misleading, the thead + tbody of Tablepress GUI is meant instead, the spanned rows have been moved as <th> into the <thead> in final HTML.

You can download and try it from the [tablepress-rowspan-all](https://github.com/strarsis/tablepress-rowspan-all) repository.
With the plugin installed + enabled it is possible to use `#rowspan#` in the rows below the rows in thead.

There seems to be no easy way changing the backend GUI e.g. for adding new controls by plugin.

**Comment by strarsis** [comment]
Ideally TablePress would offer a numeric input for the number of thead/tfoot rows and also visually highlight them (blue background) as currently with the first thead row.
This would also avoid the need for extra handling of rowspans between thead and tbody section in GUI.

**Comment by TobiasBg** [comment]
At the moment, I don't think that this is really necessary as a UI. I'd rather first make this reliably and robustly usable using a filter hook. Only if that's used by a significant number of people would a user interface make sense.

**Comment by SolidSnakeLive** [comment]
Please allow this feature, I use first row for description and second row for filter
I tried to pass this command "orderCellsTop": false but it seems your code block it also the tick option that force first row -top- cells as header

**Comment by TobiasBg** [comment]
Hi @SolidSnakeLive,

as much as I would love to be able support this, there's no easy way at the moment, sorry :-( This would be very tricky to implement, as so much interaction with the DataTables JS library would be necessary. So, I don't think that this will be possible soon. Sorry for not having better news here.

Best wishes,
Tobias

**Comment by strarsis** [comment]
@SolidSnakeLive: You can use the [tablepress-rowspan-all](https://github.com/strarsis/tablepress-rowspan-all) plugin as workaround.

**Comment by SolidSnakeLive** [comment]
@TobiasBg Thanks for reply
@strarsis Thanks for info

**Comment by strarsis** [comment]
@TobiasBg: With 2.x lots of UI was added, nice!
Even the rowspan extension still works, which means backwards compatibility is still preserved.

Is with 2.x multiple rows/rowspan support possible/planned for the table header? 🐱

**Comment by TobiasBg** [comment]
Hi @strarsis,

good to hear that you like TablePress 2.0.

At this time, I don't have such plans though, sorry :-(
