### ISSUE TITLE
"Table with header cells in first column only"

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#58]
Is it possible with TablePress to create ["Tables with header cells in first column only"](https://www.w3.org/WAI/tutorials/tables/one-header/#table-with-header-cells-in-the-first-column-only)? 

In first column the cell should be a table header cell (th) which 
is useful or even required for some kind of tabular data.

**Comment by TobiasBg** [comment]
Yes, this is possible, you can use the `first_column_th` Shortcode parameter, see https://tablepress.org/faq/documentation-shortcode-table/.
