### ISSUE TITLE
How Can I make Automatic URL conversion by Default?

### ISSUE THREAD

**Issue by Dibbyo456** [TobiasBg/TablePress#59]

**Comment by TobiasBg** [comment]
Hi @Dibbyo456,

for that, you'll need to make a small change to the "tablepress-automatic-url-conversion.php" file.
Please change line 27 from
`$default_atts['automatic_url_conversion'] = false;`
to
`$default_atts['automatic_url_conversion'] = true;`

Regards,
Tobias
