### ISSUE TITLE
Output table as raw data

### ISSUE THREAD

**Issue by mjharris2407** [TobiasBg/TablePress#60]
If there was an option to bring the tables to the front end as raw data (json, array, etc). This would enable many new features. The admin area is exceptional for managing data inside the wordpress area vs. some other interface to the database. 

This would let me use tablepress as a version controlled micro database for small page specific components. (Example: A map with a list of points)

I'm able to get this to work by modifying template files but it would be so much more useful to be able to use a shortcode.
`  $table = TablePress::$controller->model_table->load( $the_table_id );`
` echo "<script> var table_data = " .json_encode( $table['data']). "</script>";`

**Comment by TobiasBg** [comment]
Hi,

this should not be too difficult, e.g. by using the `tablepress_table_output` filter hook:
```PHP
add_filter( 'tablepress_table_output', 'mjharris2407_tablepress_json_output', 10, 3 );
function mjharris2407_tablepress_json_output( $output, $table, $render_options ) {
  $output = "<script> var table_data = " . json_encode( $table['data'] ). "</script>";
  return $output;
}```
You could also include a check for a custom Shortcode parameter, similar to how the existing TablePress Extensions do it.
