### ISSUE TITLE
Incompatibility with qTranslate-X

### ISSUE THREAD

**Issue by gabrielecker** [TobiasBg/TablePress#62]
The settings from any table editing form (e.g. Table options and DataTables stuff) seems to not be applied to the table rendered in posts when qTranslate-X plugin is activated as well. Not sure if the problem is the translate plugin though.

**Comment by TobiasBg** [comment]
Hi,

thanks for your post, and sorry for the trouble. I can't really imagine that the translation plugin would cause this, as it should not be interfering with the JavaScript code.
Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by gabrielecker** [comment]
Unfortunately I've only simulated this in a private development environment, will try to find something for you, thanks :)

**Comment by TobiasBg** [comment]
That would be great, thanks! Also, could you maybe check if there are any JavaScript errors in the error log console of the browser? And most importantly: Is the JS invocation code in the page (via "View Source" in the browser)?

**Comment by gabrielecker** [comment]
I looked into the network requests for my web page and apparently something weird is happening, when I activate the translate plugin there is a file called datatables.whatever.js requested and when the translate plugin is deactivated this file doesn't seem to be requested. Hope this helps with something

**Comment by TobiasBg** [comment]
That jquery.datatables.min.js file is the JavaScript file from TablePress that contains the relevant code for those JS features from TablePress. So, that's mandatory for these features to work. Or are you referring to a different file?

**Comment by gabrielecker** [comment]
Actually I know a bit about what happened there: I disabled all the DataTables options in the table settings so it didn't import the script since it was not necessary (this is the right case without the translate plugin).
However with the translate plugin for some reason it keeps requesting this script even though it's not needed.

**Comment by TobiasBg** [comment]
TablePress will load that script if the "Use DataTables" checkbox is checked (regardless off the state of the checkboxes for the individual features), or if a TablePress Extension is active for that table that might require it.
But I guess a direct look at a page where this happens would be the best approach here.

**Comment by gabrielecker** [comment]
There's a link to a page where this is happening: http://teste.paginas.ufsc.br/2017/06/06/table-test/
And my settings are as follows:
![wp_tablepress_configs](https://user-images.githubusercontent.com/12613996/26836458-45e3ff06-4ab1-11e7-820d-d8e4d3a05eb8.png)
As you can see they are not working (e. g. first row as header, pagination limit as 1)

**Comment by TobiasBg** [comment]
Thanks for the link and screenshot! Are you sure that this is really the same table that we are talking about here? The main issue here is that the "Table Head Row" checkbox is checked but the first row is not marked as such.
Are there maybe any Shortcode parameters used on that page?

**Comment by gabrielecker** [comment]
Yup, I cleaned any tables to make sure this is the only one there.
I'm using the simple Shortcode "[table id=1 /]" not sure if any parameters are needed in this case.

**Comment by TobiasBg** [comment]
Ok, really strange then... If possible, I'd like to take a direct look at this on your site. Could you therefore please create a temporary admin account for me and send me the details via email (the address is in the main plugin file "tablepress.php")? That way, I can investigate this directly. Thanks!

**Comment by gabrielecker** [comment]
I'll see what I can do :) probably will take some time though. Thanks for your attention for now.

**Comment by TobiasBg** [comment]
HI @gabrielecker,

did you find anything in your tests?

Best wishes,
Tobias

**Comment by gabrielecker** [comment]
Hi @TobiasBg ,

I've been looking at it and it seems like the problem is with qTranslate-X which is blocking the datatables javascript import, i'm still not sure where exactly this is happening still.

Thanks,
Gabriel

**Comment by TobiasBg** [comment]
Hi @gabrielecker,

thanks for checking! Would you be ok with me closing this issue for now, as I just don't see how TablePress is doing something wrong here? Of course, if you find that this issue is TablePress' fault, we can always reopen! Thanks!

Best wishes,
Tobias

**Comment by gabrielecker** [comment]
Yeah, i'll debug the whole thing to find out what is really going on and warn you if I discover anything important. For now we are fine with that :)
Thanks for the support,
Gabriel
