### ISSUE TITLE
Options are autoloaded by default

### ISSUE THREAD

**Issue by daveross** [TobiasBg/TablePress#63]
TablePress_WP_Option::_update_option calls update_option with two parameters. Leaving off the third parameter lets WordPress default the option to autoload. This isn't always ideal, especially if there's a bunch of other options being autoloaded and object caching is in use.

Would it make sense to pass that third parameter and only autoload really important TablePress options?

**Comment by TobiasBg** [comment]
Hi @daveross,

Thanks for your feedback!
TablePress actually only uses two options (in the `wp_options` database table), namely `tablepress_tables` and `tablepress_options`.
Both are necessary very early during runtime of a page request, so I think it makes sense here, would you agree?

Thanks!
Tobias

**Comment by daveross** [comment]
Two isn't so bad. We run into issues once in a while where all a site's autoloaded options get stored in a single memcache value and the total size goes over the 1mb default limit. So I keep an eye out for that kind of thing. It's definitely a balancing act between performance and rare issues like this, though.
