### ISSUE TITLE
serverside table query supoort

### ISSUE THREAD

**Issue by kerneltravel** [TobiasBg/TablePress#68]
Hi, I've implement the serverside tablepress based on tablepress and ColumnFilterWidgets plugins, currently just an working one, with some little bug. 
so as GPL required, where shall I submit the patch ?

**Comment by TobiasBg** [comment]
Hi @kerneltravel,

very cool, that sounds great! If you want, just add this as a repo in your GitHub account. Alternatively, you could send me the new files via email (the address is in the main plugin file "tablepress.php"), and I'll add them to the plugin.

Best wishes,
Tobias
