### ISSUE TITLE
how to make a summary row at bottom and fix it to prevent sorting effect

### ISSUE THREAD

**Issue by iamkanp** [TobiasBg/TablePress#71]
@TobiasBg 
how to make a summary row at bottom and fix it to prevent sorting effect?
Thanks in advance,
Kan P.

**Comment by TobiasBg** [comment]
Hi,

thanks for your post, and sorry for the trouble.

For this, just check the "Table Footer" checkbox on the table's "Edit" screen.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @iamkanp,

did this help?

Regards,
Tobias
