### ISSUE TITLE
TablePress and Wordpress Search function

### ISSUE THREAD

**Issue by effetx** [TobiasBg/TablePress#72]
Hello,
I'm developing a website with a large use of tables made with TablePress. The plugin is amazing but I have a problem with the Wordpress search function.  I saw that this feature has already been discussed [here](https://github.com/TobiasBg/TablePress/issues/39). I try to disable all plugins with no results. 
At the moment the website is this [temporary web address](http://vps362583.ovh.net) . Have you any suggestion to solve my problem?
Thanks a lot,
Francesco

**Comment by TobiasBg** [comment]
Hi @effetx,

this is a problem that came up with the recent WordPress 4.8.2 release. I'm already testing a solution and I will release a new version soon.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi again,

if you want to test this, you can try this patch:
```diff
--- controllers/controller-frontend.php
+++ controllers/controller-frontend.php
@@ -875,6 +875,7 @@ JS;
 		// If $_GET['exact'] is set, WordPress doesn't use % in SQL LIKE clauses.
 		$exact = get_query_var( 'exact' );
 		$n = ( empty( $exact ) ) ? '%' : '';
+		$search_sql = $wpdb->remove_placeholder_escape( $search_sql );
 		foreach ( $query_result as $search_term => $table_ids ) {
 			$search_term = esc_sql( $wpdb->esc_like( $search_term ) );
 			$old_or = "OR ({$wpdb->posts}.post_content LIKE '{$n}{$search_term}{$n}')";
@@ -883,6 +884,7 @@ JS;
 			$new_or = $old_or . " OR ({$wpdb->posts}.post_content REGEXP '{$regexp}')";
 			$search_sql = str_replace( $old_or, $new_or, $search_sql );
 		}
+		$search_sql = $wpdb->add_placeholder_escape( $search_sql );

 		return $search_sql;
 	}
--
```

**Comment by effetx** [comment]
Hi @TobiasBg ,
Thank you very much for the very quick answer (and sorry for my poor english). I immediately try your patch but unfortunately I don't see any change. I tried again to disable all plugin except TablePress but no result.

**Comment by TobiasBg** [comment]
Hi @effetx,

ah, that's strange. If possible, I'd like to take a direct look at this on your site. Could you therefore please get in touch via email (the address is in the main plugin file "tablepress.php")? That way, I can investigate this directly. Thanks!

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

we found that updating to WordPress 4.9 and using the patch fixed this :-)

Regards,
Tobias
