### ISSUE TITLE
Export of column containing text and dates

### ISSUE THREAD

**Issue by wopl** [TobiasBg/TablePress#73]
I have a column that shows (alternatively) single dates (01.01.2018), just month and year (01.2018) or time-spans (01.01.2018 - 31.01.2018). All of this should be exported, edited in Excel and imported again.
Unfortunately the entries are handled cell by cell to decide correct formatting (I'd wish all of them are handled as text), which Excel is not capable to interpret correctly.
Putting a leading apostroph in Excel allows a correct import. Exporting it again the formatting gets odd again.

Thanks for having a look.
And thanks for the (otherwise) very nice plugin.
Wolfram

**Comment by TobiasBg** [comment]
Hi @wopl,

thanks for your question, and sorry for the trouble.

What file formats are you using in both directions of the import and export here? For this, I recommend using the CSV format. TablePress will always interpret the content as text then, and from everything I know, Excel will also reduce format conversions then.

Regards,
Tobias

**Comment by wopl** [comment]
Hi Tobias,
I initially used the CSV, where my problem appeared. Further investigation showed, that I might have to use the xlsx format to avoid the problem. Not sure yet. Nevertheless, I solved my problem using the Excel as a source to import. 
But just to repeat: export will corrupt the fields which I can handle now, but other users may not be aware of and will distroy their data base. 

Nevertheless many thanks for provideing this tool, which I started to use extensively. 

Best regards,
Wolfram

**Comment by TobiasBg** [comment]
Hi,

are you sure that exporting to a CSV file from TablePress breaks the data? What does the CSV file look like in a text editor?

Regards,
Tobias

**Comment by wopl** [comment]
Hi Tobias,
o.k., I have to apologize. I just opened with Excel and did not verify the file itself. The CSV is correct, but the import to Excel does some weired things with the content.
Sorry again for misleading.
Thanks and best regards,
Wolfram

**Comment by TobiasBg** [comment]
Hi Wolfram,

thanks for the confirmation! Yes, Excel does weird thinks here sometimes. I even had the case that opening the .csv file with a double click lead to a different result than opening it from within Excel...

Best wishes,
Tobias
