### ISSUE TITLE
Huge amount of rows cause high ram usage and load times

### ISSUE THREAD

**Issue by bykidi** [TobiasBg/TablePress#74]
Hello!
First of all - this is dope plugin. Saved so much of my time. Thank you for it.
But here is what the main problem: how can i reduce the amount of rows displayed at once?
![default](https://user-images.githubusercontent.com/1337953/35088998-a9548622-fc46-11e7-967f-34ec885cd381.png)

**Comment by bykidi** [comment]
NEVERMIND! :)
![default](https://user-images.githubusercontent.com/1337953/35089069-dde80288-fc46-11e7-8707-554d07dc86f6.png)
But also having that in the editor could be good too

**Comment by TobiasBg** [comment]
Hi,

yes, for the frontend, the Pagination option is the best.
Unfortunately, that's not yet available on the "Edit" screen. I plan to make this faster by completely rewriting that screen, but that will still take time

In the meantime, I recommend to try other browsers (some handle the many fields better than others), or to maintain the table e.g. in Excel and re-import it into TablePress after making changes.

Regards,
Tobias
