### ISSUE TITLE
Contributing Tablepress Pods extension

### ISSUE THREAD

**Issue by gwhitney** [TobiasBg/TablePress#76]
Dear Tobias,
  Tablepress is a natural fit to go with the Pods plugin for Wordpress (which helps create and use custom post types and taxonomies). With the attached extension, one can effortlessly create tables which summarize and display information about the content in Pods custom post types and taxonomies. The combination is easily a match for commercial plugins like Posts Table Pro.
  In an effort to support and foster Tablepress, I am contributing the extension to Tablepress and releasing its source code under the identical license as Tablepress itself (GPL v2).
  Please let me know if you decide to adopt it into the Tablepress distribution. If not, I will seek other means for distributing it, as I believe it will be useful to others. With 500K active installs, I strongly suspect that other Tablepress users are also using Pods, which itself has over 50K active installs.
  If you would like me to draft a page concerning this plugin (along the lines of https://tablepress.org/extensions/table-shortcode/ etc.) please just let me know.
  Best regards, Glen
[tablepress-pods.zip](https://github.com/TobiasBg/TablePress/files/1755770/tablepress-pods.zip)

**Comment by TobiasBg** [comment]
Hi @gwhitney,

Just as for your other contribution: I'm a bit busy and don't have the time to test it thoroughly at the moment, especially since I haven't used Pods myself, yet. So how about you maybe publish this as a git repo in your account, at least for the meantime? That would probably be the best approach for now.

Best wishes,
Tobias

**Comment by gwhitney** [comment]
Dear Tobias,
  I have finally managed to post the tablepress-pods extension as a git repository: https://code.studioinfinity.org/glen/tablepress-pods
As I suggested in #77, it might be generally beneficial for you to create a page on your site listing 3rd party extensions to Tablepress -- just a thought.

**Comment by Rooi-Els** [comment]
Dear @gwhitney,

Would it be possible to ask your help on an issue I'm having with your Pods extension. If I'm not posting in the right place, please just refer me to the proper place to post this. I am new to Github.

So I have a pod called "application"  and I want to list all applications made by the current user. 
I have the following columns in TablePress:

```
Username                                    Vacancy Title
{@applicant_username}                       <a href= "{@permalink, esc_url}" > {@vacancy_title} </a>
```

The only shortcode I've gotten to work is the following:

`[table id=2 pod_name="application" /]`

But this will list all the users that have applied for all vacancies. I want to only list the applications done by the current user. 

I have tried several variations of the following shortcode, but it doesn't work:

`[table id=2 pod_name="application" pod_where="t.applicant_username = user_login" /]`

I've also tried adding the following shortcode in php:

```
if ( function_exists( 'tablepress_get_table' ) ) {
  add_shortcode( 'table-user-filtered', 'tablepress_filtered_table' );
  function tablepress_filtered_table( $atts ) {
    if ( ! is_user_logged_in() ) {
      return 'Error: No user is logged in.';
    }
    $current_user = wp_get_current_user();
    $applicant_username = $current_user->user_login;
    $atts['filter'] = $applicant_username;
    $atts['filter_full_cell_match'] = true;
    $atts['cache_table_output'] = false;
    return tablepress_get_table( $atts ) ;
  }
}
```
and then using this shortcode:

`[table-user-filtered id=2 pod_name="application" /]`

but this does nothing as well.

Any help you can offer at this stage will be much appreciated!

And thanks so much for this plugin, it really ads a much needed dimension to tablepress!

Kind Regards,
Michael

**Comment by gwhitney** [comment]
@Rooi-Els I have moved this issue to https://code.studioinfinity.org/glen/tablepress-pods/issues/10 and will respond there.
