### ISSUE TITLE
Contributing Tablepress Datatables Colrejigger extension

### ISSUE THREAD

**Issue by gwhitney** [TobiasBg/TablePress#77]
Dear Tobias,
  This is another Tablepress extension that I would be happy to contribute to the project. It follows very closely the outlines of your existing Tablepress Datatables extensions. This one wraps the Datatables Colreorder and Colresize extensions (the latter is third-party) so that Datatables column order and column widths can be altered in the front end on the fly, by dragging in the column headers. Again, I am happy to draft a documentation webpage if it would be helpful. Let me know whether you decide to incorporate this into your distribution. If not, then suggestions would be welcome on where to post this so interested parties may find it.
[tablepress-datatables-colrejigger.zip](https://github.com/TobiasBg/TablePress/files/1755772/tablepress-datatables-colrejigger.zip)

  Best regards, Glen

**Comment by TobiasBg** [comment]
Hi @gwhitney,

thanks for sharing this Extension, I really appreciate it!

I'm a bit busy and don't have the time to test it thoroughly at the moment, therefore it might take a while until I could add it to the TablePress website (as this would mean that I would have to offer support for the Extension). So how about you maybe publish this as a git repo in your account, at least for the meantime?

Best wishes,
Tobias

**Comment by gwhitney** [comment]
Dear Tobias,
Thank you for the advice. I have finally had a chance to do as you suggest. Anyone interested can find the TablePress DataTables ColRejigger extension at https://code.studioinfinity.org/glen/tablepress-datatables-colrejigger
If you might possibly be able to make a page on your main site pointing people to 3rd party extensions of TablePress (not just mine of course), it might be mutually beneficial. Just a suggestion.
