### ISSUE TITLE
License "GPL2" is not a valid SPDX license identifier

### ISSUE THREAD

**Issue by sebastianthulin** [TobiasBg/TablePress#79]
License "GPL2" is not a valid SPDX license identifier, see https://spdx.org/licenses/. This is an issue since packagist cannot update the package at https://packagist.org/packages/tobiasbg/tablepress. 

Packagist: "This package is in a broken state and will not update anymore. Some branches contain invalid data and until you fix them the entire package is frozen. Click "Force Update" above to see details.".

**Comment by TobiasBg** [comment]
Hi @sebastianthulin,

from what I can see `GPL-2.0-only` should be the new proper identifier there. Can you confirm that?

Thanks!
Tobias

**Comment by sebastianthulin** [comment]
Yeah. That seems like the appropriate one. :)
