### ISSUE TITLE
Make TablePress callable through the REST API

### ISSUE THREAD

**Issue by yannj-fr** [TobiasBg/TablePress#80]
Hello,

Are TablePress data retreivable through the wordpress rest api?
From browsing the code it seems the answer is no but I just want to double check.

**Comment by TobiasBg** [comment]
Hi @yannj-fr,

no, sorry, this is not yet possible. For some background, please see https://wordpress.org/support/topic/fetch-tablepress-data-via-wordpress-api/

Best wishes,
Tobias

**Comment by OmarACY** [comment]
Hello,

Are TablePress data retreivable through the wordpress rest api?
From browsing the code it seems the answer is no but I just want to double check.

**Comment by TobiasBg** [comment]
Hi @OmarACY,

no, sorry, this is still not possible. The answer from above still applies.

Regards,
Tobias
