### ISSUE TITLE
Date's value changed

### ISSUE THREAD

**Issue by dhaval47** [TobiasBg/TablePress#81]
I have one xlsx file of full of orders. While importing it on TablePress value of date is changed to some numbers.

My data are as below.

```
Date
1/2/2018 0:00
1/2/2018 0:00
1/4/2018 0:00
1/6/2018 0:00
1/10/2018 0:00
1/10/2018 0:00
1/14/2018 0:00
1/14/2018 0:00
1/14/2018 0:00
1/14/2018 0:00
1/14/2018 0:00
1/15/2018 0:00
1/15/2018 0:00
1/15/2018 0:00
1/15/2018 0:00
```

Output in TablePress is below.
<table id="tablepress-8" class="tablepress tablepress-id-8 dataTable no-footer" role="grid" aria-describedby="tablepress-8_info">
<thead>
<tr class="row-1 odd" role="row"><th class="column-1 sorting" tabindex="0" aria-controls="tablepress-8" rowspan="1" colspan="1" aria-label="Date: activate to sort column ascending" style="width: 1715px;">Date</th></tr>
</thead>
<tbody class="row-hover">
<tr class="row-2 even" role="row">
	<td class="column-1">43102</td>
</tr><tr class="row-3 odd" role="row">
	<td class="column-1">43102</td>
</tr><tr class="row-4 even" role="row">
	<td class="column-1">43104</td>
</tr><tr class="row-5 odd" role="row">
	<td class="column-1">43106</td>
</tr><tr class="row-6 even" role="row">
	<td class="column-1">43110</td>
</tr><tr class="row-7 odd" role="row">
	<td class="column-1">43110</td>
</tr><tr class="row-8 even" role="row">
	<td class="column-1">43114</td>
</tr><tr class="row-9 odd" role="row">
	<td class="column-1">43114</td>
</tr><tr class="row-10 even" role="row">
	<td class="column-1">43114</td>
</tr><tr class="row-11 odd" role="row">
	<td class="column-1">43114</td>
</tr></tbody>
</table>

Please help.

**Comment by TobiasBg** [comment]
Hi @dhaval47,

thanks for your post, and sorry for the trouble.

Please try this again after saving the table to a CSV file from Excel, and import that. With that method, these things are usually kept.

Regards,
Tobias

**Comment by dhaval47** [comment]
Actually these xlsx files are auto generated by shopkeepers and I am using **TablePress Extension: Table Auto Update** plugin so I can't change xlsx file to csv every time because it should be automated.

**Comment by TobiasBg** [comment]
Hi,

ah, that's unfortunate. Unfortunately, I can't really think of a solution here then :-( The import from .xlsx is not that good and flexible, unfortunately. It doesn't recognize different time/date formats, unfortunately.
I'm really sorry.

Regards,
Tobias

**Comment by vreemt** [comment]
Hi, just as a note, the numbers are how Excel stores dates. They're serial
numbers and can be displayed as dates or converted.
In an automated process with no control over how the files are generated, I
would write a data pre-processor to help make the dates recognisable for
people and TablePress.

More information on Excel's date serial numbers:
https://support.office.com/en-us/article/DATEVALUE-function-DF8B07D4-7761-4A93-BC33-B7471BBFF252
Displaying a serial number as a date is done with the formula `=VALUE() `

Hope that helps.
Sandra.

Op ma 16 apr. 2018 10:42 schreef Dhaval <notifications@github.com>:

**Comment by TobiasBg** [comment]
Hi,

thanks for this input! This is definitely good to know, and maybe it can be used to make the Excel import better in the future!

Best wishes,
Tobias

**Comment by dhaval47** [comment]
Hi,

I changed order of column and dates display correctly now.
I know its strange but worked for me.

Thanks a lot for wonderful plugin @TobiasBg
