### ISSUE TITLE
Row classes confilct

### ISSUE THREAD

**Issue by dkvadratu** [TobiasBg/TablePress#82]
Hi. Maybe change or add prefix (ex. tp-) to plugin classes, because i had css styling confilt with [theme](https://themeforest.net/item/yellow-bussun-construction-theme-for-industrial-businesses/21130075) and it may occur more often, because class "row-1" might want use any other dev.

Solution: replace `$row_classes = 'row-' . ( $row_idx + 1 );` to `$row_classes = 'tp-row-' . ( $row_idx + 1 );`
File: classes/class-render.php (ln 687)

**Comment by TobiasBg** [comment]
Hi @dkvadratu,

unfortunately, it's too late to change this in TablePress now, for backward-compatibility reasons. Many users already have CSS in place that uses `.row-...`.

If there is a conflict with your theme, your best chance is to overwrite the CSS with something like
`.tablepress .row-... {
  ...
}`

Best wishes,
Tobias
