### ISSUE TITLE
Move the count up e rename

### ISSUE THREAD

**Issue by Alexisback** [TobiasBg/TablePress#96]
Hello,
I need help
I would like to move the "counting" description up and change the name of the description

which file and where to edit?

thank you

![2018-09-22_14-10-44](https://user-images.githubusercontent.com/18039740/45916623-e8bbbe00-be71-11e8-8906-1bb2e4cd427a.png)

**Comment by TobiasBg** [comment]
Hi @Alexisback,

this is possible using a "Custom Command", which you need to enter on the table's "Edit" screen:
`"dom": "lifrtp"`
This follows the documentation at https://datatables.net/reference/option/dom. Every letter is a different element.

To change the wording/text, you can use the TablePress Extension from https://tablepress.org/extensions/change-datatables-strings/.

Regards,
Tobias

**Comment by Alexisback** [comment]
Hi Tobiasbg,
I really am not very experienced (in truth I did not understand anything) :(
could you kindly illustrate the procedure for doing this?

grzaie again

**Comment by TobiasBg** [comment]
Hi @Alexisback,

I'm not sure how I can help more. Please find the "Custom Commands" text field in the "Feature of the DataTables library" section on the "Edit" screen of your table. There, add the command
`"dom": "lifrtp"`

For the other part, install the Extension from the link as a new plugin, and make the necessary modification in the .json file.

Regards,
Tobias
