### ISSUE TITLE
Wrong counting in the tables

### ISSUE THREAD

**Issue by Alexisback** [TobiasBg/TablePress#97]
finally, I managed to enter the count, above (not found the "Custom Commands" because in my and another language)

I noticed a problem,
when the cells are all empty the count is wrong (example: value "4" in this case)
the correct value is "0"

why?
![2018-09-22_16-57-04](https://user-images.githubusercontent.com/18039740/45918001-b8cbe500-be88-11e8-907d-d082280354b3.png)

**Comment by TobiasBg** [comment]
Hi @Alexisback,

no, the count here is correct. The table still shows 4 rows, which is the number that is shown. If you want 0, you must delete all empty rows from your table.

(A side note: For support questions like this, please use the forums at https://wordpress.org/support/plugin/tablepress/ next time. I'd like to use Github Issues for actual bugs only.)

Regards,
Tobias

**Comment by Alexisback** [comment]
solved the mystery, the rows were 4, but empty
OK thanks

ps: I will go in the "forum" in the future for my questions

**Comment by TobiasBg** [comment]
Hi,

yes, that's what I meant :-)

Best wishes,
Tobias
