### ISSUE TITLE
Exporting data from MySQL directly

### ISSUE THREAD

**Issue by dchenk** [TobiasBg/TablePress#98]
Is there a reason I wouldn't be able to export the `post` records of type `tablepress_table` with all `postmeta` directly from the database and import this into another WP installation? I did this process for all other post types successfully. And the data is in the new database, but in the All Tables tab no tables are being listed. It's important for me for the tables to keep the same IDs across the migration.

Looking forward to some help on this. Thank you.

**Comment by TobiasBg** [comment]
Hi @dchenk,

in addition to all these entries, you will also need the `tablepress_tables` and `tablepress_options` entries from the `wp_options` DB table. These hold the mapping between table ID and WordPress post ID, and some settings.

You could also use the "Export" option in TablePress for the migration, using the JSON format. This will also transfer all data, including every table's options, including the ID.

Regards,
Tobias
