### ISSUE TITLE
I want to use this plugin in multisite(Network) environment

### ISSUE THREAD

**Issue by reach2rahulbharti** [TobiasBg/TablePress#99]
Actually I have site which multi site for different country.
i want to create tablerpess shortcode for the post, submitted in one click in multisite...

Is it possible or not ???

**Comment by TobiasBg** [comment]
Hi @reach2rahulbharti,

as you have also opened a forums thread at https://wordpress.org/support/topic/i-want-to-use-this-plugin-in-multisitenetwork-environment/ I will reply there, as that's the better place for support.

Best wishes,
Tobias
